//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
export const ALLOWED_TAGS = new Set([
  "a",
  "abbr",
  "address",
  "article",
  "aside",
  "b",
  "bdi",
  "bdo",
  "blockquote",
  "br",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "dd",
  "del",
  "details",
  "dfn",
  "div",
  "dl",
  "dt",
  "em",
  "figcaption",
  "figure",
  "footer",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "header",
  "hr",
  "i",
  "img",
  "ins",
  "kbd",
  "li",
  "main",
  "mark",
  "nav",
  "ol",
  "p",
  "picture",
  "pre",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "section",
  "small",
  "source",
  "span",
  "strike",
  "strong",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "tfoot",
  "th",
  "thead",
  "time",
  "tr",
  "u",
  "ul",
  "var",
  "wbr",
  "font",
  "center",
  "style",
]);

export const DANGEROUS_TAGS = new Set([
  "script",
  "iframe",
  "object",
  "embed",
  "form",
  "input",
  "button",
  "select",
  "textarea",
  "applet",
  "base",
  "basefont",
  "bgsound",
  "frame",
  "frameset",
  "ilayer",
  "layer",
  "link",
  "meta",
  "noscript",
  "xml",
  "svg",
  "math",
  "foreignObject",
  "use",
  "set",
  "animate",
  "animateTransform",
  "animateMotion",
  "mpath",
  "clipPath",
  "defs",
  "desc",
  "feBlend",
  "feGaussianBlur",
  "filter",
  "g",
  "line",
  "linearGradient",
  "marker",
  "mask",
  "pattern",
  "polygon",
  "polyline",
  "radialGradient",
  "rect",
  "stop",
  "symbol",
  "text",
  "tspan",
]);

export const ALLOWED_ATTRIBUTES: Record<string, Set<string>> = {
  "*": new Set([
    "class",
    "id",
    "title",
    "dir",
    "lang",
    "style",
    "data-aster-signature",
    "data-aster-signature-id",
  ]),
  a: new Set(["href", "target", "rel", "name"]),
  img: new Set(["src", "alt", "width", "height", "loading", "srcset"]),
  div: new Set(["align"]),
  p: new Set(["align"]),
  span: new Set(["align"]),
  td: new Set([
    "colspan",
    "rowspan",
    "align",
    "valign",
    "width",
    "height",
    "bgcolor",
    "background",
  ]),
  th: new Set([
    "colspan",
    "rowspan",
    "align",
    "valign",
    "width",
    "height",
    "bgcolor",
    "background",
  ]),
  table: new Set([
    "cellpadding",
    "cellspacing",
    "border",
    "width",
    "height",
    "align",
    "bgcolor",
    "background",
  ]),
  tr: new Set(["align", "valign", "bgcolor", "background"]),
  col: new Set(["span", "width"]),
  colgroup: new Set(["span", "width"]),
  font: new Set(["color", "face", "size"]),
  source: new Set(["src", "srcset", "type", "media"]),
  ol: new Set(["start", "type", "reversed"]),
  li: new Set(["value"]),
  blockquote: new Set(["cite"]),
  q: new Set(["cite"]),
  time: new Set(["datetime"]),
  data: new Set(["value"]),
  h1: new Set(["align"]),
  h2: new Set(["align"]),
  h3: new Set(["align"]),
  h4: new Set(["align"]),
  h5: new Set(["align"]),
  h6: new Set(["align"]),
};

export const DANGEROUS_URL_SCHEMES = new Set([
  "javascript:",
  "vbscript:",
  "file:",
]);

export const DANGEROUS_CSS_PATTERNS = [
  /expression\s*\(/i,
  /javascript\s*:/i,
  /vbscript\s*:/i,
  /behavior\s*:/i,
  /-moz-binding/i,
  /paint\s*\(/i,
  /-moz-document/i,
];

export const ALLOWED_DATA_URL_TYPES = new Set([
  "data:image/jpeg",
  "data:image/jpg",
  "data:image/png",
  "data:image/gif",
  "data:image/webp",
  "data:image/avif",
  "data:image/bmp",
  "data:image/tiff",
  "data:image/heic",
  "data:image/heif",
  "data:image/x-icon",
  "data:image/vnd.microsoft.icon",
]);

export const TRACKING_PIXEL_PATTERNS = [
  /width\s*[:=]\s*["']?[01](?!\d)/i,
  /height\s*[:=]\s*["']?[01](?!\d)/i,
];

export const TRACKING_PIXEL_URL_PATTERNS = [
  /\/track/i,
  /\/open\//i,
  /\/pixel/i,
  /\/beacon/i,
  /\/wf\/open/i,
  /\/o\.gif/i,
  /\/t\.gif/i,
  /\/e\.gif/i,
  /(?:^|[./])mailchimp\.com.*\/track/i,
  /(?:^|[./])list-manage\.com.*\/track/i,
  /(?:^|[./])sendgrid\.net.*\/wf\//i,
  /(?:^|[./])amazonses\.com(?:\/|$)/i,
  /(?:^|[./])doubleclick\.net(?:\/|$)/i,
  /(?:^|[./])mailgun\.org.*\/o\//i,
  /(?:^|[./])sparkpostmail(?:\/|$)/i,
  /(?:^|[./])returnpath\.net(?:\/|$)/i,
  /emltrk\./i,
  /bsn\.sendgrid/i,
];

export const TRACKING_PARAMS = new Set([
  "utm_source",
  "utm_medium",
  "utm_campaign",
  "utm_term",
  "utm_content",
  "utm_id",
  "fbclid",
  "gclid",
  "gclsrc",
  "dclid",
  "gbraid",
  "wbraid",
  "msclkid",
  "twclid",
  "li_fat_id",
  "mc_cid",
  "mc_eid",
  "oly_anon_id",
  "oly_enc_id",
  "_openstat",
  "vero_id",
  "wickedid",
  "yclid",
  "rb_clickid",
  "s_cid",
  "ml_subscriber",
  "ml_subscriber_hash",
  "igshid",
  "ref_src",
  "ref_url",
  "trk",
  "trkCampaign",
  "trkInfo",
  "sc_campaign",
  "sc_channel",
  "sc_content",
  "sc_medium",
  "sc_outcome",
  "sc_geo",
  "sc_country",
]);

export const MAX_CSS_PX = 1200;

export const COMPOSE_ALLOWED_CSS_PROPERTIES = new Set([
  "color",
  "background-color",
  "font-size",
  "font-weight",
  "font-style",
  "font-family",
  "text-align",
  "text-decoration",
  "text-transform",
  "letter-spacing",
  "white-space",
  "line-height",
  "border",
  "border-top",
  "border-right",
  "border-bottom",
  "border-left",
  "border-inline-start",
  "border-inline-end",
  "border-width",
  "border-style",
  "border-color",
  "border-collapse",
  "border-spacing",
  "border-radius",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "padding",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "padding-inline-start",
  "padding-inline-end",
  "margin",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "margin-inline-start",
  "margin-inline-end",
  "max-width",
  "min-width",
  "max-height",
  "min-height",
  "height",
  "width",
  "table-layout",
  "object-fit",
  "float",
  "clear",
  "list-style-type",
  "list-style-position",
  "direction",
  "unicode-bidi",
  "display",
  "vertical-align",
]);

export const COMPOSE_ALLOWED_DISPLAY_VALUES = new Set([
  "block",
  "inline",
  "inline-block",
  "table",
  "inline-table",
  "table-row",
  "table-cell",
  "table-row-group",
  "table-header-group",
  "table-footer-group",
  "table-column",
  "table-column-group",
  "table-caption",
]);

export const COMPOSE_ALLOWED_VERTICAL_ALIGN_VALUES = new Set([
  "baseline",
  "top",
  "middle",
  "bottom",
  "text-top",
  "text-bottom",
]);
