//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//
export interface EmojiEntry {
  emoji: string;
  keywords: string[];
}

export interface EmojiCategory {
  label: string;
  icon: string;
  entries: EmojiEntry[];
}

export const emoji_categories: Record<string, EmojiCategory> = {
  smileys: {
    label: "Smileys & People",
    icon: "😊",
    entries: [
      { emoji: "😀", keywords: ["grinning", "happy", "smile"] },
      { emoji: "😃", keywords: ["grinning", "big eyes", "happy"] },
      { emoji: "😄", keywords: ["grinning", "squinting", "happy", "laugh"] },
      { emoji: "😁", keywords: ["beaming", "grin", "happy"] },
      { emoji: "😆", keywords: ["squinting", "laugh", "happy"] },
      { emoji: "😅", keywords: ["sweat", "grinning", "nervous"] },
      { emoji: "🤣", keywords: ["rofl", "rolling", "laughing", "lol"] },
      { emoji: "😂", keywords: ["joy", "crying", "laughing", "tears", "lol"] },
      { emoji: "🙂", keywords: ["slightly smiling", "ok"] },
      { emoji: "🙃", keywords: ["upside down", "sarcasm"] },
      { emoji: "😉", keywords: ["wink", "winking"] },
      { emoji: "😊", keywords: ["blush", "smiling", "happy", "warm"] },
      { emoji: "😇", keywords: ["angel", "halo", "innocent"] },
      { emoji: "🥰", keywords: ["love", "hearts", "adore", "smiling"] },
      { emoji: "😍", keywords: ["heart eyes", "love", "crush"] },
      { emoji: "🤩", keywords: ["star struck", "excited", "wow"] },
      { emoji: "😘", keywords: ["kiss", "blowing kiss", "love"] },
      { emoji: "😗", keywords: ["kissing", "pucker"] },
      { emoji: "☺️", keywords: ["smiling", "relaxed", "happy"] },
      { emoji: "😚", keywords: ["kissing", "closed eyes"] },
      { emoji: "😙", keywords: ["kissing", "smiling eyes"] },
      { emoji: "🥲", keywords: ["smiling", "tear", "sad", "proud"] },
      { emoji: "😋", keywords: ["yummy", "delicious", "tongue"] },
      { emoji: "😛", keywords: ["tongue", "playful"] },
      { emoji: "😜", keywords: ["wink", "tongue", "crazy", "zany"] },
      { emoji: "🤪", keywords: ["zany", "crazy", "wild", "goofy"] },
      { emoji: "😝", keywords: ["squinting", "tongue"] },
      { emoji: "🤑", keywords: ["money", "rich", "dollar"] },
      { emoji: "🤗", keywords: ["hug", "hugging", "open hands"] },
      { emoji: "🤭", keywords: ["hand over mouth", "oops", "giggle"] },
      { emoji: "🫢", keywords: ["open eyes", "hand over mouth", "surprise"] },
      { emoji: "🫣", keywords: ["peeking", "shy", "hiding"] },
      { emoji: "🤫", keywords: ["shh", "quiet", "secret", "shush"] },
      { emoji: "🤔", keywords: ["thinking", "hmm", "consider"] },
      { emoji: "🫡", keywords: ["salute", "respect"] },
      { emoji: "🤐", keywords: ["zipper mouth", "quiet", "secret"] },
      { emoji: "🤨", keywords: ["raised eyebrow", "skeptical", "suspicious"] },
      { emoji: "😐", keywords: ["neutral", "blank", "indifferent"] },
      { emoji: "😑", keywords: ["expressionless", "blank"] },
      { emoji: "😶", keywords: ["no mouth", "silent", "speechless"] },
      { emoji: "🫥", keywords: ["dotted line", "invisible", "hidden"] },
      { emoji: "😏", keywords: ["smirk", "smug", "sly"] },
      { emoji: "😒", keywords: ["unamused", "annoyed", "meh"] },
      { emoji: "🙄", keywords: ["eye roll", "annoyed", "whatever"] },
      { emoji: "😬", keywords: ["grimace", "awkward", "nervous"] },
      { emoji: "🫨", keywords: ["shaking", "shock"] },
      { emoji: "😮‍💨", keywords: ["exhale", "sigh", "relief"] },
      { emoji: "🤥", keywords: ["lying", "pinocchio", "liar"] },
      { emoji: "🫠", keywords: ["melting", "dissolving", "hot"] },
      { emoji: "😌", keywords: ["relieved", "peaceful", "calm"] },
      { emoji: "😔", keywords: ["pensive", "sad", "thoughtful"] },
      { emoji: "😪", keywords: ["sleepy", "tired", "tear"] },
      { emoji: "🤤", keywords: ["drooling", "hungry", "want"] },
      { emoji: "😴", keywords: ["sleeping", "zzz", "tired"] },
      { emoji: "😷", keywords: ["mask", "sick", "medical"] },
      { emoji: "🤒", keywords: ["thermometer", "sick", "fever"] },
      { emoji: "🤕", keywords: ["bandage", "hurt", "injured"] },
      { emoji: "🤢", keywords: ["nauseated", "sick", "green"] },
      { emoji: "🤮", keywords: ["vomiting", "sick", "puke"] },
      { emoji: "🥵", keywords: ["hot", "sweating", "heat"] },
      { emoji: "🥶", keywords: ["cold", "freezing", "ice"] },
      { emoji: "🥴", keywords: ["woozy", "dizzy", "drunk"] },
      { emoji: "😵", keywords: ["dizzy", "knocked out"] },
      { emoji: "😵‍💫", keywords: ["dizzy", "spiral", "confused"] },
      { emoji: "🤯", keywords: ["exploding head", "mind blown", "shocked"] },
      { emoji: "🤠", keywords: ["cowboy", "hat", "yeehaw"] },
      { emoji: "🥳", keywords: ["party", "celebrate", "birthday", "hat"] },
      { emoji: "🥸", keywords: ["disguise", "glasses", "nose"] },
      { emoji: "😎", keywords: ["sunglasses", "cool", "confident"] },
      { emoji: "🤓", keywords: ["nerd", "glasses", "geek"] },
      { emoji: "🧐", keywords: ["monocle", "inspect", "curious"] },
      { emoji: "😕", keywords: ["confused", "puzzled"] },
      { emoji: "🫤", keywords: ["diagonal mouth", "unsure", "meh"] },
      { emoji: "😟", keywords: ["worried", "concerned"] },
      { emoji: "🙁", keywords: ["slightly frowning", "sad"] },
      { emoji: "☹️", keywords: ["frowning", "sad"] },
      { emoji: "😮", keywords: ["open mouth", "surprised"] },
      { emoji: "😯", keywords: ["hushed", "surprised", "stunned"] },
      { emoji: "😲", keywords: ["astonished", "shocked", "wow"] },
      { emoji: "😳", keywords: ["flushed", "embarrassed", "surprised"] },
      { emoji: "🥺", keywords: ["pleading", "puppy eyes", "please"] },
      { emoji: "🥹", keywords: ["holding back tears", "touched", "grateful"] },
      { emoji: "😦", keywords: ["frowning", "open mouth"] },
      { emoji: "😧", keywords: ["anguished", "shocked"] },
      { emoji: "😨", keywords: ["fearful", "scared", "afraid"] },
      { emoji: "😰", keywords: ["anxious", "sweat", "worried"] },
      { emoji: "😥", keywords: ["sad", "relieved", "disappointed"] },
      { emoji: "😢", keywords: ["crying", "sad", "tear"] },
      { emoji: "😭", keywords: ["sobbing", "crying", "wailing", "sad"] },
      { emoji: "😱", keywords: ["screaming", "fear", "horror", "scared"] },
      { emoji: "😖", keywords: ["confounded", "frustrated"] },
      { emoji: "😣", keywords: ["persevering", "struggling"] },
      { emoji: "😞", keywords: ["disappointed", "sad"] },
      { emoji: "😓", keywords: ["downcast", "sweat", "sad"] },
      { emoji: "😩", keywords: ["weary", "tired", "exhausted"] },
      { emoji: "😫", keywords: ["tired", "frustrated"] },
      { emoji: "🥱", keywords: ["yawning", "bored", "tired"] },
      { emoji: "😤", keywords: ["huffing", "angry", "frustrated", "triumph"] },
      { emoji: "😡", keywords: ["angry", "pouting", "mad", "rage"] },
      { emoji: "😠", keywords: ["angry", "mad", "grumpy"] },
      { emoji: "🤬", keywords: ["swearing", "cursing", "angry", "symbols"] },
      { emoji: "😈", keywords: ["devil", "evil", "smiling", "horns"] },
      { emoji: "👿", keywords: ["angry devil", "imp", "evil"] },
      { emoji: "💀", keywords: ["skull", "dead", "death", "skeleton"] },
      { emoji: "☠️", keywords: ["skull crossbones", "death", "danger"] },
      { emoji: "💩", keywords: ["poop", "poo", "pile"] },
      { emoji: "🤡", keywords: ["clown", "joker", "funny"] },
      { emoji: "👹", keywords: ["ogre", "monster", "demon"] },
      { emoji: "👺", keywords: ["goblin", "tengu", "mask"] },
      { emoji: "👻", keywords: ["ghost", "halloween", "spooky"] },
      { emoji: "👽", keywords: ["alien", "ufo", "extraterrestrial"] },
      { emoji: "👾", keywords: ["alien monster", "space invader", "game"] },
      { emoji: "🤖", keywords: ["robot", "machine", "bot"] },
      { emoji: "😺", keywords: ["cat", "smiling", "happy"] },
      { emoji: "😸", keywords: ["cat", "grinning", "happy"] },
      { emoji: "😹", keywords: ["cat", "tears", "joy", "laugh"] },
      { emoji: "😻", keywords: ["cat", "heart eyes", "love"] },
      { emoji: "😼", keywords: ["cat", "smirk", "wry"] },
      { emoji: "😽", keywords: ["cat", "kiss"] },
      { emoji: "🙀", keywords: ["cat", "weary", "surprised"] },
      { emoji: "😿", keywords: ["cat", "crying", "sad"] },
      { emoji: "😾", keywords: ["cat", "pouting", "angry"] },
      { emoji: "🙈", keywords: ["monkey", "see no evil"] },
      { emoji: "🙉", keywords: ["monkey", "hear no evil"] },
      { emoji: "🙊", keywords: ["monkey", "speak no evil"] },
    ],
  },
  gestures: {
    label: "Hands & Body",
    icon: "👋",
    entries: [
      { emoji: "👋", keywords: ["wave", "hello", "bye", "hand"] },
      { emoji: "🤚", keywords: ["raised back", "hand", "stop"] },
      { emoji: "🖐️", keywords: ["hand", "fingers", "splayed"] },
      { emoji: "✋", keywords: ["raised hand", "high five", "stop"] },
      { emoji: "🖖", keywords: ["vulcan", "spock", "star trek"] },
      { emoji: "🫱", keywords: ["rightward hand"] },
      { emoji: "🫲", keywords: ["leftward hand"] },
      { emoji: "🫳", keywords: ["palm down hand"] },
      { emoji: "🫴", keywords: ["palm up hand"] },
      { emoji: "🫷", keywords: ["leftward pushing hand"] },
      { emoji: "🫸", keywords: ["rightward pushing hand"] },
      { emoji: "👌", keywords: ["ok", "perfect", "fine"] },
      { emoji: "🤌", keywords: ["pinched fingers", "italian"] },
      { emoji: "🤏", keywords: ["pinching", "small", "tiny", "little"] },
      { emoji: "✌️", keywords: ["victory", "peace", "two"] },
      { emoji: "🤞", keywords: ["crossed fingers", "luck", "hope"] },
      { emoji: "🫰", keywords: ["hand with index finger and thumb crossed"] },
      { emoji: "🤟", keywords: ["love you", "ily", "hand"] },
      { emoji: "🤘", keywords: ["rock on", "metal", "horns"] },
      { emoji: "🤙", keywords: ["call me", "shaka", "hang loose"] },
      { emoji: "👈", keywords: ["point left", "direction"] },
      { emoji: "👉", keywords: ["point right", "direction"] },
      { emoji: "👆", keywords: ["point up", "direction"] },
      { emoji: "🖕", keywords: ["middle finger"] },
      { emoji: "👇", keywords: ["point down", "direction"] },
      { emoji: "☝️", keywords: ["index", "point up"] },
      { emoji: "🫵", keywords: ["index pointing at viewer", "you"] },
      { emoji: "👍", keywords: ["thumbs up", "like", "approve", "yes"] },
      { emoji: "👎", keywords: ["thumbs down", "dislike", "no"] },
      { emoji: "✊", keywords: ["raised fist", "power"] },
      { emoji: "👊", keywords: ["fist bump", "punch"] },
      { emoji: "🤛", keywords: ["left fist bump"] },
      { emoji: "🤜", keywords: ["right fist bump"] },
      { emoji: "👏", keywords: ["clap", "applause", "bravo"] },
      { emoji: "🙌", keywords: ["raising hands", "hooray", "celebrate"] },
      { emoji: "🫶", keywords: ["heart hands", "love"] },
      { emoji: "👐", keywords: ["open hands", "jazz hands"] },
      { emoji: "🤲", keywords: ["palms up", "prayer", "cupped"] },
      { emoji: "🤝", keywords: ["handshake", "deal", "agreement"] },
      { emoji: "🙏", keywords: ["pray", "please", "thank you", "namaste"] },
      { emoji: "✍️", keywords: ["writing", "hand"] },
      { emoji: "💅", keywords: ["nail polish", "beauty", "nails"] },
      { emoji: "🤳", keywords: ["selfie", "phone", "photo"] },
      { emoji: "💪", keywords: ["muscle", "strong", "flex", "bicep"] },
      { emoji: "🦾", keywords: ["mechanical arm", "prosthetic", "robot"] },
      { emoji: "🦿", keywords: ["mechanical leg", "prosthetic"] },
      { emoji: "🦵", keywords: ["leg", "kick"] },
      { emoji: "🦶", keywords: ["foot", "kick"] },
      { emoji: "👂", keywords: ["ear", "listen", "hear"] },
      { emoji: "🦻", keywords: ["ear with hearing aid"] },
      { emoji: "👃", keywords: ["nose", "smell"] },
      { emoji: "🧠", keywords: ["brain", "smart", "think", "intelligent"] },
      { emoji: "🫀", keywords: ["anatomical heart", "organ"] },
      { emoji: "🫁", keywords: ["lungs", "breathe"] },
      { emoji: "🦷", keywords: ["tooth", "dentist"] },
      { emoji: "🦴", keywords: ["bone", "skeleton"] },
      { emoji: "👀", keywords: ["eyes", "look", "see", "watching"] },
      { emoji: "👁️", keywords: ["eye", "see", "look"] },
      { emoji: "👅", keywords: ["tongue", "taste", "lick"] },
      { emoji: "👄", keywords: ["mouth", "lips", "kiss"] },
      { emoji: "🫦", keywords: ["biting lip", "nervous", "flirt"] },
      { emoji: "👶", keywords: ["baby", "infant", "child"] },
      { emoji: "🧒", keywords: ["child", "kid"] },
      { emoji: "👦", keywords: ["boy", "male", "child"] },
      { emoji: "👧", keywords: ["girl", "female", "child"] },
      { emoji: "🧑", keywords: ["person", "adult"] },
      { emoji: "👱", keywords: ["blond", "blonde", "person"] },
      { emoji: "👨", keywords: ["man", "male", "guy"] },
      { emoji: "🧔", keywords: ["beard", "man"] },
      { emoji: "👩", keywords: ["woman", "female", "lady"] },
      { emoji: "🧓", keywords: ["older person", "elder"] },
      { emoji: "👴", keywords: ["old man", "grandfather"] },
      { emoji: "👵", keywords: ["old woman", "grandmother"] },
      { emoji: "🙍", keywords: ["person frowning", "sad"] },
      { emoji: "🙎", keywords: ["person pouting", "annoyed"] },
      { emoji: "🙅", keywords: ["person gesturing no", "stop"] },
      { emoji: "🙆", keywords: ["person gesturing ok"] },
      { emoji: "💁", keywords: ["person tipping hand", "info"] },
      { emoji: "🙋", keywords: ["person raising hand", "question"] },
      { emoji: "🧏", keywords: ["deaf person"] },
      { emoji: "🙇", keywords: ["person bowing", "sorry"] },
      { emoji: "🤦", keywords: ["facepalm", "smh", "disbelief"] },
      { emoji: "🤷", keywords: ["shrug", "idk", "dunno", "whatever"] },
      { emoji: "🧑‍⚕️", keywords: ["health worker", "doctor", "nurse"] },
      { emoji: "🧑‍🎓", keywords: ["student", "graduate"] },
      { emoji: "🧑‍🏫", keywords: ["teacher", "professor"] },
      {
        emoji: "🧑‍💻",
        keywords: ["technologist", "programmer", "coder", "developer"],
      },
      { emoji: "🧑‍🔬", keywords: ["scientist", "researcher"] },
      { emoji: "🧑‍🎨", keywords: ["artist", "painter"] },
      { emoji: "🧑‍🚀", keywords: ["astronaut", "space"] },
      { emoji: "🧑‍🚒", keywords: ["firefighter"] },
      { emoji: "👮", keywords: ["police", "officer", "cop"] },
      { emoji: "🕵️", keywords: ["detective", "spy"] },
      { emoji: "💂", keywords: ["guard", "royal"] },
      { emoji: "🥷", keywords: ["ninja", "stealth"] },
      { emoji: "👷", keywords: ["construction worker", "builder"] },
      { emoji: "🫅", keywords: ["person with crown", "royalty"] },
      { emoji: "🤴", keywords: ["prince", "royalty"] },
      { emoji: "👸", keywords: ["princess", "royalty"] },
      { emoji: "🧙", keywords: ["mage", "wizard", "magic"] },
      { emoji: "🧚", keywords: ["fairy", "magic"] },
      { emoji: "🧛", keywords: ["vampire", "dracula"] },
      { emoji: "🧜", keywords: ["merperson", "mermaid"] },
      { emoji: "🧝", keywords: ["elf", "fantasy"] },
      { emoji: "🧞", keywords: ["genie", "magic", "lamp"] },
      { emoji: "🧟", keywords: ["zombie", "undead"] },
      { emoji: "🧌", keywords: ["troll"] },
      { emoji: "💆", keywords: ["person getting massage", "relax"] },
      { emoji: "💇", keywords: ["person getting haircut", "salon"] },
      { emoji: "🚶", keywords: ["person walking"] },
      { emoji: "🧍", keywords: ["person standing"] },
      { emoji: "🧎", keywords: ["person kneeling"] },
      { emoji: "🏃", keywords: ["person running", "exercise"] },
      { emoji: "💃", keywords: ["woman dancing", "dance"] },
      { emoji: "🕺", keywords: ["man dancing", "dance", "disco"] },
      { emoji: "👯", keywords: ["people with bunny ears", "dancers"] },
      { emoji: "🧖", keywords: ["person in steamy room", "sauna"] },
      { emoji: "🧗", keywords: ["person climbing", "rock"] },
      { emoji: "🤸", keywords: ["person cartwheeling", "gymnastics"] },
      { emoji: "🏌️", keywords: ["person golfing", "golf"] },
      { emoji: "🏇", keywords: ["horse racing", "jockey"] },
      { emoji: "⛷️", keywords: ["skier", "skiing", "snow"] },
      { emoji: "🏂", keywords: ["snowboarder", "snow", "winter"] },
      { emoji: "🏋️", keywords: ["person lifting weights", "gym"] },
      { emoji: "🤼", keywords: ["people wrestling"] },
      { emoji: "🤽", keywords: ["person playing water polo"] },
      { emoji: "🤾", keywords: ["person playing handball"] },
      { emoji: "🤺", keywords: ["person fencing", "sword"] },
      { emoji: "⛹️", keywords: ["person bouncing ball", "basketball"] },
      { emoji: "🏊", keywords: ["person swimming", "pool"] },
      { emoji: "🚣", keywords: ["person rowing boat"] },
      {
        emoji: "🧘",
        keywords: ["person in lotus position", "yoga", "meditate"],
      },
      { emoji: "🛀", keywords: ["person taking bath", "bathtub"] },
      { emoji: "🛌", keywords: ["person in bed", "sleeping"] },
      { emoji: "👭", keywords: ["women holding hands"] },
      { emoji: "👫", keywords: ["woman and man holding hands", "couple"] },
      { emoji: "👬", keywords: ["men holding hands"] },
      { emoji: "💏", keywords: ["kiss", "couple"] },
      { emoji: "💑", keywords: ["couple with heart", "love"] },
      { emoji: "👪", keywords: ["family"] },
      { emoji: "🗣️", keywords: ["speaking head", "talking"] },
      { emoji: "👤", keywords: ["bust", "silhouette", "person"] },
      { emoji: "👥", keywords: ["busts", "silhouettes", "people", "group"] },
      { emoji: "🫂", keywords: ["people hugging", "hug", "embrace"] },
      { emoji: "👣", keywords: ["footprints", "feet", "tracks"] },
    ],
  },
  animals: {
    label: "Animals & Nature",
    icon: "🐾",
    entries: [
      { emoji: "🐶", keywords: ["dog", "puppy", "pet"] },
      { emoji: "🐱", keywords: ["cat", "kitten", "pet"] },
      { emoji: "🐭", keywords: ["mouse", "rat"] },
      { emoji: "🐹", keywords: ["hamster", "pet"] },
      { emoji: "🐰", keywords: ["rabbit", "bunny"] },
      { emoji: "🦊", keywords: ["fox", "cunning"] },
      { emoji: "🐻", keywords: ["bear", "teddy"] },
      { emoji: "🐼", keywords: ["panda", "bear"] },
      { emoji: "🐻‍❄️", keywords: ["polar bear", "arctic"] },
      { emoji: "🐨", keywords: ["koala", "australia"] },
      { emoji: "🐯", keywords: ["tiger", "cat"] },
      { emoji: "🦁", keywords: ["lion", "king", "mane"] },
      { emoji: "🐮", keywords: ["cow", "moo"] },
      { emoji: "🐷", keywords: ["pig", "oink"] },
      { emoji: "🐸", keywords: ["frog", "toad"] },
      { emoji: "🐵", keywords: ["monkey", "ape"] },
      { emoji: "🙈", keywords: ["see no evil", "monkey"] },
      { emoji: "🙉", keywords: ["hear no evil", "monkey"] },
      { emoji: "🙊", keywords: ["speak no evil", "monkey"] },
      { emoji: "🐒", keywords: ["monkey", "primate"] },
      { emoji: "🐔", keywords: ["chicken", "hen", "poultry"] },
      { emoji: "🐧", keywords: ["penguin", "arctic", "cold"] },
      { emoji: "🐦", keywords: ["bird", "tweet"] },
      { emoji: "🐤", keywords: ["chick", "baby", "bird"] },
      { emoji: "🐣", keywords: ["hatching", "chick", "egg"] },
      { emoji: "🐥", keywords: ["chick", "bird", "baby"] },
      { emoji: "🦆", keywords: ["duck", "quack"] },
      { emoji: "🦅", keywords: ["eagle", "bird", "freedom"] },
      { emoji: "🦉", keywords: ["owl", "wise", "night"] },
      { emoji: "🦇", keywords: ["bat", "vampire", "night"] },
      { emoji: "🐺", keywords: ["wolf", "howl"] },
      { emoji: "🐗", keywords: ["boar", "wild pig"] },
      { emoji: "🐴", keywords: ["horse", "pony"] },
      { emoji: "🦄", keywords: ["unicorn", "magic", "fantasy"] },
      { emoji: "🫎", keywords: ["moose", "elk"] },
      { emoji: "🐝", keywords: ["bee", "honeybee", "buzz"] },
      { emoji: "🪱", keywords: ["worm"] },
      { emoji: "🐛", keywords: ["bug", "caterpillar", "insect"] },
      { emoji: "🦋", keywords: ["butterfly", "insect", "beautiful"] },
      { emoji: "🐌", keywords: ["snail", "slow"] },
      { emoji: "🐞", keywords: ["ladybug", "ladybird", "insect"] },
      { emoji: "🐜", keywords: ["ant", "insect"] },
      { emoji: "🪰", keywords: ["fly", "insect"] },
      { emoji: "🪲", keywords: ["beetle", "insect"] },
      { emoji: "🪳", keywords: ["cockroach", "bug"] },
      { emoji: "🦟", keywords: ["mosquito", "insect"] },
      { emoji: "🦗", keywords: ["cricket", "insect"] },
      { emoji: "🕷️", keywords: ["spider", "arachnid"] },
      { emoji: "🕸️", keywords: ["spider web", "cobweb"] },
      { emoji: "🦂", keywords: ["scorpion"] },
      { emoji: "🐢", keywords: ["turtle", "tortoise", "slow"] },
      { emoji: "🐍", keywords: ["snake", "reptile"] },
      { emoji: "🦎", keywords: ["lizard", "reptile"] },
      { emoji: "🦖", keywords: ["dinosaur", "t-rex", "trex"] },
      { emoji: "🦕", keywords: ["dinosaur", "sauropod", "brontosaurus"] },
      { emoji: "🐙", keywords: ["octopus", "sea"] },
      { emoji: "🦑", keywords: ["squid", "sea"] },
      { emoji: "🦐", keywords: ["shrimp", "prawn", "sea"] },
      { emoji: "🦞", keywords: ["lobster", "sea"] },
      { emoji: "🦀", keywords: ["crab", "sea"] },
      { emoji: "🪸", keywords: ["coral", "reef", "sea"] },
      { emoji: "🐡", keywords: ["blowfish", "puffer", "sea"] },
      { emoji: "🐠", keywords: ["tropical fish", "sea"] },
      { emoji: "🐟", keywords: ["fish", "sea"] },
      { emoji: "🐬", keywords: ["dolphin", "sea", "ocean"] },
      { emoji: "🐳", keywords: ["whale", "spout", "ocean"] },
      { emoji: "🐋", keywords: ["whale", "ocean"] },
      { emoji: "🦈", keywords: ["shark", "ocean", "jaws"] },
      { emoji: "🐊", keywords: ["crocodile", "alligator"] },
      { emoji: "🐅", keywords: ["tiger", "big cat"] },
      { emoji: "🐆", keywords: ["leopard", "cheetah"] },
      { emoji: "🦓", keywords: ["zebra", "stripes"] },
      { emoji: "🫏", keywords: ["donkey"] },
      { emoji: "🦍", keywords: ["gorilla", "ape"] },
      { emoji: "🦧", keywords: ["orangutan", "ape"] },
      { emoji: "🐘", keywords: ["elephant", "big"] },
      { emoji: "🦣", keywords: ["mammoth", "prehistoric"] },
      { emoji: "🦛", keywords: ["hippopotamus", "hippo"] },
      { emoji: "🦏", keywords: ["rhinoceros", "rhino"] },
      { emoji: "🐪", keywords: ["camel", "desert"] },
      { emoji: "🐫", keywords: ["camel", "two humps"] },
      { emoji: "🦒", keywords: ["giraffe", "tall"] },
      { emoji: "🦘", keywords: ["kangaroo", "australia"] },
      { emoji: "🦬", keywords: ["bison", "buffalo"] },
      { emoji: "🐃", keywords: ["water buffalo"] },
      { emoji: "🐂", keywords: ["ox", "bull"] },
      { emoji: "🐄", keywords: ["cow", "dairy"] },
      { emoji: "🐎", keywords: ["horse", "racing"] },
      { emoji: "🐖", keywords: ["pig", "hog"] },
      { emoji: "🐏", keywords: ["ram", "sheep"] },
      { emoji: "🐑", keywords: ["sheep", "lamb", "ewe"] },
      { emoji: "🦙", keywords: ["llama", "alpaca"] },
      { emoji: "🐐", keywords: ["goat"] },
      { emoji: "🦌", keywords: ["deer", "stag"] },
      { emoji: "🐕", keywords: ["dog", "pet"] },
      { emoji: "🐩", keywords: ["poodle", "dog"] },
      { emoji: "🦮", keywords: ["guide dog"] },
      { emoji: "🐕‍🦺", keywords: ["service dog"] },
      { emoji: "🐈", keywords: ["cat", "pet"] },
      { emoji: "🐈‍⬛", keywords: ["black cat"] },
      { emoji: "🪶", keywords: ["feather", "bird"] },
      { emoji: "🐓", keywords: ["rooster", "chicken"] },
      { emoji: "🦃", keywords: ["turkey", "thanksgiving"] },
      { emoji: "🦚", keywords: ["peacock", "bird"] },
      { emoji: "🦜", keywords: ["parrot", "bird", "tropical"] },
      { emoji: "🦢", keywords: ["swan", "bird", "elegant"] },
      { emoji: "🦩", keywords: ["flamingo", "pink"] },
      { emoji: "🕊️", keywords: ["dove", "peace", "bird"] },
      { emoji: "🐇", keywords: ["rabbit", "bunny"] },
      { emoji: "🦝", keywords: ["raccoon", "trash panda"] },
      { emoji: "🦨", keywords: ["skunk", "stink"] },
      { emoji: "🦡", keywords: ["badger"] },
      { emoji: "🦫", keywords: ["beaver", "dam"] },
      { emoji: "🦦", keywords: ["otter", "sea", "cute"] },
      { emoji: "🦥", keywords: ["sloth", "lazy", "slow"] },
      { emoji: "🐁", keywords: ["mouse", "rodent"] },
      { emoji: "🐀", keywords: ["rat", "rodent"] },
      { emoji: "🐿️", keywords: ["chipmunk", "squirrel"] },
      { emoji: "🦔", keywords: ["hedgehog", "prickly"] },
      { emoji: "🐾", keywords: ["paw prints", "pet", "animal"] },
      { emoji: "🐉", keywords: ["dragon", "fantasy"] },
      { emoji: "🐲", keywords: ["dragon face", "chinese"] },
      { emoji: "🌵", keywords: ["cactus", "desert"] },
      { emoji: "🎄", keywords: ["christmas tree", "holiday"] },
      { emoji: "🌲", keywords: ["evergreen", "tree", "pine"] },
      { emoji: "🌳", keywords: ["deciduous tree", "tree"] },
      { emoji: "🌴", keywords: ["palm tree", "tropical", "beach"] },
      { emoji: "🪵", keywords: ["wood", "log"] },
      { emoji: "🌱", keywords: ["seedling", "grow", "plant"] },
      { emoji: "🌿", keywords: ["herb", "plant", "green"] },
      { emoji: "☘️", keywords: ["shamrock", "clover", "irish"] },
      { emoji: "🍀", keywords: ["four leaf clover", "lucky", "luck"] },
      { emoji: "🎍", keywords: ["bamboo", "decoration"] },
      { emoji: "🪴", keywords: ["potted plant", "houseplant"] },
      { emoji: "🎋", keywords: ["tanabata tree"] },
      { emoji: "🍃", keywords: ["leaf", "wind", "nature"] },
      { emoji: "🍂", keywords: ["fallen leaf", "autumn", "fall"] },
      { emoji: "🍁", keywords: ["maple leaf", "canada", "fall"] },
      { emoji: "🪺", keywords: ["nest with eggs", "bird"] },
      { emoji: "🪹", keywords: ["empty nest"] },
      { emoji: "🍄", keywords: ["mushroom", "fungi"] },
      { emoji: "🌾", keywords: ["rice", "grain", "plant"] },
      { emoji: "💐", keywords: ["bouquet", "flowers"] },
      { emoji: "🌷", keywords: ["tulip", "flower", "spring"] },
      { emoji: "🌹", keywords: ["rose", "flower", "love"] },
      { emoji: "🥀", keywords: ["wilted flower", "dead"] },
      { emoji: "🪻", keywords: ["hyacinth", "flower"] },
      { emoji: "🌺", keywords: ["hibiscus", "flower", "tropical"] },
      { emoji: "🌸", keywords: ["cherry blossom", "flower", "spring"] },
      { emoji: "🌼", keywords: ["blossom", "flower"] },
      { emoji: "🌻", keywords: ["sunflower", "flower"] },
      { emoji: "🌞", keywords: ["sun with face", "sunny"] },
      { emoji: "🌝", keywords: ["moon with face", "night"] },
      { emoji: "🌛", keywords: ["first quarter moon face"] },
      { emoji: "🌜", keywords: ["last quarter moon face"] },
      { emoji: "🌚", keywords: ["new moon face", "creepy"] },
      { emoji: "🌕", keywords: ["full moon"] },
      { emoji: "🌖", keywords: ["waning gibbous moon"] },
      { emoji: "🌗", keywords: ["last quarter moon"] },
      { emoji: "🌘", keywords: ["waning crescent moon"] },
      { emoji: "🌑", keywords: ["new moon"] },
      { emoji: "🌒", keywords: ["waxing crescent moon"] },
      { emoji: "🌓", keywords: ["first quarter moon"] },
      { emoji: "🌔", keywords: ["waxing gibbous moon"] },
      { emoji: "🌙", keywords: ["crescent moon", "night"] },
      {
        emoji: "🌍",
        keywords: ["globe", "earth", "europe", "africa", "world"],
      },
      { emoji: "🌎", keywords: ["globe", "earth", "americas", "world"] },
      { emoji: "🌏", keywords: ["globe", "earth", "asia", "world"] },
      { emoji: "🪐", keywords: ["planet", "saturn", "ring", "space"] },
      { emoji: "💫", keywords: ["dizzy", "star", "shooting"] },
      { emoji: "⭐", keywords: ["star", "yellow"] },
      { emoji: "🌟", keywords: ["glowing star", "sparkle"] },
      { emoji: "✨", keywords: ["sparkles", "magic", "clean"] },
      { emoji: "⚡", keywords: ["lightning", "bolt", "electricity", "zap"] },
      { emoji: "☄️", keywords: ["comet", "meteor"] },
      { emoji: "💥", keywords: ["boom", "collision", "explosion"] },
      { emoji: "🔥", keywords: ["fire", "hot", "lit"] },
      { emoji: "🌪️", keywords: ["tornado", "twister"] },
      { emoji: "🌈", keywords: ["rainbow", "colorful"] },
      { emoji: "☀️", keywords: ["sun", "sunny", "bright"] },
      { emoji: "🌤️", keywords: ["sun behind small cloud"] },
      { emoji: "⛅", keywords: ["sun behind cloud"] },
      { emoji: "🌥️", keywords: ["sun behind large cloud"] },
      { emoji: "☁️", keywords: ["cloud", "overcast"] },
      { emoji: "🌦️", keywords: ["sun behind rain cloud"] },
      { emoji: "🌧️", keywords: ["rain", "cloud with rain"] },
      { emoji: "⛈️", keywords: ["thunder", "storm", "lightning"] },
      { emoji: "🌩️", keywords: ["cloud with lightning"] },
      { emoji: "🌨️", keywords: ["cloud with snow"] },
      { emoji: "❄️", keywords: ["snowflake", "cold", "winter"] },
      { emoji: "☃️", keywords: ["snowman", "winter", "cold"] },
      { emoji: "⛄", keywords: ["snowman", "winter"] },
      { emoji: "🌬️", keywords: ["wind", "blow", "face"] },
      { emoji: "💨", keywords: ["dash", "wind", "fast"] },
      { emoji: "💧", keywords: ["droplet", "water", "sweat"] },
      { emoji: "💦", keywords: ["sweat droplets", "water", "splash"] },
      { emoji: "🌊", keywords: ["wave", "ocean", "water", "sea"] },
      { emoji: "🫧", keywords: ["bubbles", "soap"] },
    ],
  },
  food: {
    label: "Food & Drink",
    icon: "🍔",
    entries: [
      { emoji: "🍏", keywords: ["green apple", "fruit"] },
      { emoji: "🍎", keywords: ["red apple", "fruit"] },
      { emoji: "🍐", keywords: ["pear", "fruit"] },
      { emoji: "🍊", keywords: ["orange", "tangerine", "fruit"] },
      { emoji: "🍋", keywords: ["lemon", "citrus", "fruit"] },
      { emoji: "🍌", keywords: ["banana", "fruit"] },
      { emoji: "🍉", keywords: ["watermelon", "fruit", "summer"] },
      { emoji: "🍇", keywords: ["grapes", "fruit", "wine"] },
      { emoji: "🍓", keywords: ["strawberry", "fruit", "berry"] },
      { emoji: "🫐", keywords: ["blueberries", "fruit", "berry"] },
      { emoji: "🍈", keywords: ["melon", "fruit"] },
      { emoji: "🍒", keywords: ["cherries", "fruit"] },
      { emoji: "🍑", keywords: ["peach", "fruit"] },
      { emoji: "🥭", keywords: ["mango", "fruit", "tropical"] },
      { emoji: "🍍", keywords: ["pineapple", "fruit", "tropical"] },
      { emoji: "🥥", keywords: ["coconut", "tropical"] },
      { emoji: "🥝", keywords: ["kiwi", "fruit"] },
      { emoji: "🍅", keywords: ["tomato", "vegetable"] },
      { emoji: "🍆", keywords: ["eggplant", "aubergine"] },
      { emoji: "🥑", keywords: ["avocado", "guacamole"] },
      { emoji: "🫛", keywords: ["pea pod", "vegetable"] },
      { emoji: "🥦", keywords: ["broccoli", "vegetable"] },
      { emoji: "🥬", keywords: ["leafy green", "lettuce", "vegetable"] },
      { emoji: "🥒", keywords: ["cucumber", "pickle"] },
      { emoji: "🌶️", keywords: ["hot pepper", "spicy", "chili"] },
      { emoji: "🫑", keywords: ["bell pepper", "capsicum"] },
      { emoji: "🌽", keywords: ["corn", "maize"] },
      { emoji: "🥕", keywords: ["carrot", "vegetable"] },
      { emoji: "🫒", keywords: ["olive", "oil"] },
      { emoji: "🧄", keywords: ["garlic"] },
      { emoji: "🧅", keywords: ["onion"] },
      { emoji: "🥔", keywords: ["potato", "vegetable"] },
      { emoji: "🍠", keywords: ["sweet potato", "yam"] },
      { emoji: "🫘", keywords: ["beans"] },
      { emoji: "🥐", keywords: ["croissant", "bread", "french"] },
      { emoji: "🍞", keywords: ["bread", "toast", "loaf"] },
      { emoji: "🥖", keywords: ["baguette", "french bread"] },
      { emoji: "🫓", keywords: ["flatbread", "naan", "pita"] },
      { emoji: "🥨", keywords: ["pretzel", "snack"] },
      { emoji: "🥯", keywords: ["bagel", "bread"] },
      { emoji: "🥞", keywords: ["pancakes", "breakfast"] },
      { emoji: "🧇", keywords: ["waffle", "breakfast"] },
      { emoji: "🧀", keywords: ["cheese", "wedge"] },
      { emoji: "🍖", keywords: ["meat", "bone", "drumstick"] },
      { emoji: "🍗", keywords: ["poultry", "chicken leg"] },
      { emoji: "🥩", keywords: ["steak", "meat", "beef"] },
      { emoji: "🥓", keywords: ["bacon", "meat", "breakfast"] },
      { emoji: "🍔", keywords: ["hamburger", "burger", "fast food"] },
      { emoji: "🍟", keywords: ["french fries", "fries", "fast food"] },
      { emoji: "🍕", keywords: ["pizza", "slice"] },
      { emoji: "🌭", keywords: ["hot dog", "sausage"] },
      { emoji: "🥪", keywords: ["sandwich", "sub"] },
      { emoji: "🌮", keywords: ["taco", "mexican"] },
      { emoji: "🌯", keywords: ["burrito", "wrap", "mexican"] },
      { emoji: "🫔", keywords: ["tamale", "mexican"] },
      { emoji: "🥙", keywords: ["pita", "falafel", "kebab"] },
      { emoji: "🧆", keywords: ["falafel"] },
      { emoji: "🥚", keywords: ["egg"] },
      { emoji: "🍳", keywords: ["cooking", "fried egg", "breakfast"] },
      { emoji: "🥘", keywords: ["shallow pan", "paella", "cooking"] },
      { emoji: "🍲", keywords: ["pot", "stew", "soup"] },
      { emoji: "🫕", keywords: ["fondue", "cheese", "chocolate"] },
      { emoji: "🥣", keywords: ["bowl with spoon", "cereal"] },
      { emoji: "🥗", keywords: ["salad", "green", "healthy"] },
      { emoji: "🍿", keywords: ["popcorn", "movie", "snack"] },
      { emoji: "🧈", keywords: ["butter"] },
      { emoji: "🧂", keywords: ["salt", "seasoning"] },
      { emoji: "🥫", keywords: ["canned food", "tin"] },
      { emoji: "🍱", keywords: ["bento box", "japanese", "lunch"] },
      { emoji: "🍘", keywords: ["rice cracker", "japanese"] },
      { emoji: "🍙", keywords: ["rice ball", "onigiri", "japanese"] },
      { emoji: "🍚", keywords: ["cooked rice"] },
      { emoji: "🍛", keywords: ["curry rice", "indian"] },
      { emoji: "🍜", keywords: ["steaming bowl", "noodles", "ramen"] },
      { emoji: "🍝", keywords: ["spaghetti", "pasta", "italian"] },
      { emoji: "🍠", keywords: ["roasted sweet potato"] },
      { emoji: "🍢", keywords: ["oden", "skewer", "japanese"] },
      { emoji: "🍣", keywords: ["sushi", "japanese", "fish"] },
      { emoji: "🍤", keywords: ["fried shrimp", "tempura"] },
      { emoji: "🍥", keywords: ["fish cake", "narutomaki"] },
      { emoji: "🥮", keywords: ["moon cake", "chinese"] },
      { emoji: "🍡", keywords: ["dango", "japanese", "sweet"] },
      { emoji: "🥟", keywords: ["dumpling", "gyoza", "pierogi"] },
      { emoji: "🥠", keywords: ["fortune cookie"] },
      { emoji: "🥡", keywords: ["takeout box", "chinese food"] },
      { emoji: "🦀", keywords: ["crab", "seafood"] },
      { emoji: "🦞", keywords: ["lobster", "seafood"] },
      { emoji: "🦐", keywords: ["shrimp", "prawn", "seafood"] },
      { emoji: "🦑", keywords: ["squid", "calamari"] },
      { emoji: "🍦", keywords: ["ice cream", "soft serve", "dessert"] },
      { emoji: "🍧", keywords: ["shaved ice", "dessert"] },
      { emoji: "🍨", keywords: ["ice cream", "dessert", "sundae"] },
      { emoji: "🍩", keywords: ["doughnut", "donut", "dessert"] },
      { emoji: "🍪", keywords: ["cookie", "biscuit", "dessert"] },
      { emoji: "🎂", keywords: ["birthday cake", "celebration"] },
      { emoji: "🍰", keywords: ["cake", "shortcake", "dessert"] },
      { emoji: "🧁", keywords: ["cupcake", "muffin", "dessert"] },
      { emoji: "🥧", keywords: ["pie", "dessert"] },
      { emoji: "🍫", keywords: ["chocolate", "candy", "dessert"] },
      { emoji: "🍬", keywords: ["candy", "sweet"] },
      { emoji: "🍭", keywords: ["lollipop", "candy", "sweet"] },
      { emoji: "🍮", keywords: ["custard", "pudding", "flan"] },
      { emoji: "🍯", keywords: ["honey", "pot", "sweet"] },
      { emoji: "🍼", keywords: ["baby bottle", "milk"] },
      { emoji: "🥛", keywords: ["glass of milk", "dairy"] },
      { emoji: "☕", keywords: ["coffee", "hot", "tea", "drink"] },
      { emoji: "🫖", keywords: ["teapot", "tea"] },
      { emoji: "🍵", keywords: ["tea", "green tea", "drink"] },
      { emoji: "🧋", keywords: ["bubble tea", "boba", "drink"] },
      { emoji: "🍶", keywords: ["sake", "japanese", "drink"] },
      { emoji: "🍾", keywords: ["champagne", "bottle", "celebrate"] },
      { emoji: "🍷", keywords: ["wine", "glass", "drink"] },
      { emoji: "🍸", keywords: ["cocktail", "martini", "drink"] },
      { emoji: "🍹", keywords: ["tropical drink", "cocktail"] },
      { emoji: "🍺", keywords: ["beer", "mug", "drink"] },
      { emoji: "🍻", keywords: ["clinking beer mugs", "cheers"] },
      {
        emoji: "🥂",
        keywords: ["clinking glasses", "champagne", "cheers", "toast"],
      },
      { emoji: "🥃", keywords: ["tumbler", "whiskey", "drink"] },
      { emoji: "🫗", keywords: ["pouring liquid", "water"] },
      { emoji: "🥤", keywords: ["cup with straw", "soda", "drink"] },
      { emoji: "🧊", keywords: ["ice", "cube", "cold"] },
      { emoji: "🧃", keywords: ["juice box", "drink"] },
      { emoji: "🥤", keywords: ["cup with straw", "soda"] },
    ],
  },
  travel: {
    label: "Travel & Places",
    icon: "✈️",
    entries: [
      { emoji: "🚗", keywords: ["car", "automobile", "vehicle"] },
      { emoji: "🚕", keywords: ["taxi", "cab"] },
      { emoji: "🚙", keywords: ["suv", "car", "vehicle"] },
      { emoji: "🚌", keywords: ["bus", "transit"] },
      { emoji: "🚎", keywords: ["trolleybus", "transit"] },
      { emoji: "🏎️", keywords: ["racing car", "formula", "fast"] },
      { emoji: "🚓", keywords: ["police car"] },
      { emoji: "🚑", keywords: ["ambulance", "emergency"] },
      { emoji: "🚒", keywords: ["fire truck", "engine"] },
      { emoji: "🚐", keywords: ["minibus", "van"] },
      { emoji: "🛻", keywords: ["pickup truck"] },
      { emoji: "🚚", keywords: ["delivery truck", "moving"] },
      { emoji: "🚛", keywords: ["articulated lorry", "truck"] },
      { emoji: "🚜", keywords: ["tractor", "farm"] },
      { emoji: "🛵", keywords: ["motor scooter", "vespa"] },
      { emoji: "🏍️", keywords: ["motorcycle", "motorbike"] },
      { emoji: "🛺", keywords: ["auto rickshaw", "tuk tuk"] },
      { emoji: "🚲", keywords: ["bicycle", "bike", "cycling"] },
      { emoji: "🛴", keywords: ["kick scooter"] },
      { emoji: "🚏", keywords: ["bus stop", "transit"] },
      { emoji: "🛤️", keywords: ["railway track", "train"] },
      { emoji: "🚃", keywords: ["railway car", "train"] },
      { emoji: "🚋", keywords: ["tram car", "trolley"] },
      { emoji: "🚞", keywords: ["mountain railway"] },
      { emoji: "🚝", keywords: ["monorail", "train"] },
      { emoji: "🚄", keywords: ["bullet train", "high speed", "fast"] },
      { emoji: "🚅", keywords: ["bullet train", "shinkansen"] },
      { emoji: "🚆", keywords: ["train"] },
      { emoji: "🚇", keywords: ["metro", "subway"] },
      { emoji: "🚈", keywords: ["light rail"] },
      { emoji: "🚉", keywords: ["station", "train"] },
      { emoji: "✈️", keywords: ["airplane", "plane", "flight", "travel"] },
      { emoji: "🛩️", keywords: ["small airplane"] },
      { emoji: "🛫", keywords: ["departure", "takeoff", "airplane"] },
      { emoji: "🛬", keywords: ["arrival", "landing", "airplane"] },
      { emoji: "🪂", keywords: ["parachute", "skydiving"] },
      { emoji: "💺", keywords: ["seat", "airplane", "chair"] },
      { emoji: "🚁", keywords: ["helicopter", "chopper"] },
      { emoji: "🚀", keywords: ["rocket", "launch", "space"] },
      { emoji: "🛸", keywords: ["ufo", "flying saucer", "alien"] },
      { emoji: "🛶", keywords: ["canoe", "boat", "paddle"] },
      { emoji: "⛵", keywords: ["sailboat", "sailing"] },
      { emoji: "🚤", keywords: ["speedboat", "motorboat"] },
      { emoji: "🛥️", keywords: ["motor boat"] },
      { emoji: "🛳️", keywords: ["passenger ship", "cruise"] },
      { emoji: "⛴️", keywords: ["ferry", "boat"] },
      { emoji: "🚢", keywords: ["ship", "boat", "cruise"] },
      { emoji: "⚓", keywords: ["anchor", "ship", "port"] },
      { emoji: "🪝", keywords: ["hook", "fishing"] },
      { emoji: "⛽", keywords: ["fuel pump", "gas", "petrol"] },
      { emoji: "🚧", keywords: ["construction", "barrier"] },
      { emoji: "🚦", keywords: ["traffic light", "signal"] },
      { emoji: "🚥", keywords: ["horizontal traffic light"] },
      { emoji: "🗺️", keywords: ["world map", "travel"] },
      { emoji: "🗿", keywords: ["moai", "easter island", "statue"] },
      { emoji: "🗽", keywords: ["statue of liberty", "new york"] },
      { emoji: "🗼", keywords: ["tokyo tower", "japan"] },
      { emoji: "🏰", keywords: ["castle", "european"] },
      { emoji: "🏯", keywords: ["japanese castle"] },
      { emoji: "🏟️", keywords: ["stadium", "arena"] },
      { emoji: "🎡", keywords: ["ferris wheel", "amusement"] },
      { emoji: "🎢", keywords: ["roller coaster", "amusement"] },
      { emoji: "🎠", keywords: ["carousel", "merry go round"] },
      { emoji: "⛲", keywords: ["fountain", "park"] },
      { emoji: "⛱️", keywords: ["umbrella", "beach", "sun"] },
      { emoji: "🏖️", keywords: ["beach", "sand", "sun"] },
      { emoji: "🏝️", keywords: ["desert island", "tropical"] },
      { emoji: "🏜️", keywords: ["desert", "sand"] },
      { emoji: "🌋", keywords: ["volcano", "eruption"] },
      { emoji: "⛰️", keywords: ["mountain"] },
      { emoji: "🏔️", keywords: ["snow capped mountain"] },
      { emoji: "🗻", keywords: ["mount fuji", "japan"] },
      { emoji: "🏕️", keywords: ["camping", "tent"] },
      { emoji: "⛺", keywords: ["tent", "camping"] },
      { emoji: "🏠", keywords: ["house", "home"] },
      { emoji: "🏡", keywords: ["house with garden"] },
      { emoji: "🏘️", keywords: ["houses", "neighborhood"] },
      { emoji: "🏚️", keywords: ["derelict house", "abandoned"] },
      { emoji: "🏗️", keywords: ["building construction", "crane"] },
      { emoji: "🏭", keywords: ["factory", "industrial"] },
      { emoji: "🏢", keywords: ["office building"] },
      { emoji: "🏬", keywords: ["department store", "shopping"] },
      { emoji: "🏣", keywords: ["japanese post office"] },
      { emoji: "🏤", keywords: ["post office"] },
      { emoji: "🏥", keywords: ["hospital", "medical"] },
      { emoji: "🏦", keywords: ["bank", "money"] },
      { emoji: "🏨", keywords: ["hotel", "accommodation"] },
      { emoji: "🏪", keywords: ["convenience store", "shop"] },
      { emoji: "🏫", keywords: ["school", "education"] },
      { emoji: "🏩", keywords: ["love hotel"] },
      { emoji: "💒", keywords: ["wedding", "chapel"] },
      { emoji: "🏛️", keywords: ["classical building", "museum"] },
      { emoji: "⛪", keywords: ["church", "religion"] },
      { emoji: "🕌", keywords: ["mosque", "islam"] },
      { emoji: "🕍", keywords: ["synagogue", "jewish"] },
      { emoji: "🛕", keywords: ["hindu temple"] },
      { emoji: "🕋", keywords: ["kaaba", "mecca"] },
      { emoji: "⛩️", keywords: ["shinto shrine", "japan"] },
      { emoji: "🌃", keywords: ["night", "city", "starry"] },
      { emoji: "🌆", keywords: ["cityscape", "sunset"] },
      { emoji: "🌇", keywords: ["sunset", "city"] },
      { emoji: "🌉", keywords: ["bridge at night"] },
      { emoji: "🌌", keywords: ["milky way", "galaxy", "space"] },
      { emoji: "🎆", keywords: ["fireworks", "celebrate"] },
      { emoji: "🎇", keywords: ["sparkler", "fireworks"] },
    ],
  },
  objects: {
    label: "Objects",
    icon: "💡",
    entries: [
      { emoji: "⌚", keywords: ["watch", "time"] },
      { emoji: "📱", keywords: ["phone", "mobile", "cell", "smartphone"] },
      { emoji: "📲", keywords: ["phone", "call", "incoming"] },
      { emoji: "💻", keywords: ["laptop", "computer", "pc"] },
      { emoji: "⌨️", keywords: ["keyboard", "type"] },
      { emoji: "🖥️", keywords: ["desktop computer", "monitor"] },
      { emoji: "🖨️", keywords: ["printer"] },
      { emoji: "🖱️", keywords: ["computer mouse"] },
      { emoji: "🖲️", keywords: ["trackball"] },
      { emoji: "💽", keywords: ["computer disk", "minidisk"] },
      { emoji: "💾", keywords: ["floppy disk", "save"] },
      { emoji: "💿", keywords: ["cd", "disk", "optical"] },
      { emoji: "📀", keywords: ["dvd", "disk"] },
      { emoji: "📷", keywords: ["camera", "photo"] },
      { emoji: "📸", keywords: ["camera with flash", "photo"] },
      { emoji: "📹", keywords: ["video camera", "camcorder"] },
      { emoji: "🎥", keywords: ["movie camera", "film"] },
      { emoji: "📽️", keywords: ["film projector"] },
      { emoji: "🎞️", keywords: ["film frames", "movie"] },
      { emoji: "📞", keywords: ["telephone", "call"] },
      { emoji: "☎️", keywords: ["telephone", "call", "phone"] },
      { emoji: "📟", keywords: ["pager", "beeper"] },
      { emoji: "📠", keywords: ["fax machine"] },
      { emoji: "📺", keywords: ["television", "tv", "screen"] },
      { emoji: "📻", keywords: ["radio", "music"] },
      { emoji: "🎙️", keywords: ["studio microphone", "podcast"] },
      { emoji: "🎚️", keywords: ["level slider", "volume"] },
      { emoji: "🎛️", keywords: ["control knobs", "dials"] },
      { emoji: "🧭", keywords: ["compass", "navigation"] },
      { emoji: "⏱️", keywords: ["stopwatch", "timer"] },
      { emoji: "⏲️", keywords: ["timer clock"] },
      { emoji: "⏰", keywords: ["alarm clock", "wake up"] },
      { emoji: "🕰️", keywords: ["mantelpiece clock"] },
      { emoji: "⌛", keywords: ["hourglass", "time", "sand"] },
      { emoji: "⏳", keywords: ["hourglass flowing", "time"] },
      { emoji: "🔋", keywords: ["battery", "power", "charge"] },
      { emoji: "🪫", keywords: ["low battery"] },
      { emoji: "🔌", keywords: ["plug", "electric", "power"] },
      { emoji: "💡", keywords: ["light bulb", "idea", "bright"] },
      { emoji: "🔦", keywords: ["flashlight", "torch"] },
      { emoji: "🕯️", keywords: ["candle", "light", "flame"] },
      { emoji: "🧯", keywords: ["fire extinguisher"] },
      { emoji: "🗑️", keywords: ["wastebasket", "trash", "delete"] },
      { emoji: "🛢️", keywords: ["oil drum", "barrel"] },
      { emoji: "💸", keywords: ["money with wings", "spending"] },
      { emoji: "💵", keywords: ["dollar", "money", "cash"] },
      { emoji: "💴", keywords: ["yen", "money"] },
      { emoji: "💶", keywords: ["euro", "money"] },
      { emoji: "💷", keywords: ["pound", "money"] },
      { emoji: "🪙", keywords: ["coin", "money"] },
      { emoji: "💰", keywords: ["money bag", "rich", "cash"] },
      { emoji: "💳", keywords: ["credit card", "payment"] },
      { emoji: "💎", keywords: ["gem", "diamond", "jewel"] },
      { emoji: "⚖️", keywords: ["balance scale", "justice"] },
      { emoji: "🪜", keywords: ["ladder", "climb"] },
      { emoji: "🧰", keywords: ["toolbox", "tools"] },
      { emoji: "🪛", keywords: ["screwdriver", "tool"] },
      { emoji: "🔧", keywords: ["wrench", "tool", "settings"] },
      { emoji: "🔨", keywords: ["hammer", "tool", "build"] },
      { emoji: "⚒️", keywords: ["hammer and pick", "tool"] },
      { emoji: "🛠️", keywords: ["hammer and wrench", "tools"] },
      { emoji: "⛏️", keywords: ["pick", "mining"] },
      { emoji: "🪚", keywords: ["saw", "carpentry"] },
      { emoji: "🔩", keywords: ["nut and bolt", "hardware"] },
      { emoji: "⚙️", keywords: ["gear", "settings", "cog"] },
      { emoji: "🪤", keywords: ["mouse trap"] },
      { emoji: "🧲", keywords: ["magnet", "attract"] },
      { emoji: "🔫", keywords: ["water gun", "pistol", "squirt"] },
      { emoji: "💣", keywords: ["bomb", "explosive"] },
      { emoji: "🧨", keywords: ["firecracker", "dynamite"] },
      { emoji: "🪓", keywords: ["axe", "chop"] },
      { emoji: "🔪", keywords: ["kitchen knife", "cut"] },
      { emoji: "🗡️", keywords: ["dagger", "sword"] },
      { emoji: "⚔️", keywords: ["crossed swords", "battle"] },
      { emoji: "🛡️", keywords: ["shield", "defense", "protect"] },
      { emoji: "🔑", keywords: ["key", "lock", "password"] },
      { emoji: "🗝️", keywords: ["old key", "vintage"] },
      { emoji: "🔒", keywords: ["lock", "locked", "secure", "privacy"] },
      { emoji: "🔓", keywords: ["unlocked", "open"] },
      { emoji: "🔏", keywords: ["lock with pen", "privacy"] },
      { emoji: "🔐", keywords: ["locked with key", "secure"] },
      { emoji: "📧", keywords: ["email", "e-mail", "envelope"] },
      { emoji: "✉️", keywords: ["envelope", "mail", "letter"] },
      { emoji: "📨", keywords: ["incoming envelope", "email"] },
      { emoji: "📩", keywords: ["envelope with arrow", "email"] },
      { emoji: "📤", keywords: ["outbox tray", "sent"] },
      { emoji: "📥", keywords: ["inbox tray", "received"] },
      { emoji: "📦", keywords: ["package", "box", "delivery"] },
      { emoji: "📫", keywords: ["mailbox", "mail"] },
      { emoji: "📪", keywords: ["mailbox", "empty"] },
      { emoji: "📬", keywords: ["mailbox with mail"] },
      { emoji: "📭", keywords: ["mailbox", "no mail"] },
      { emoji: "📮", keywords: ["postbox", "mail"] },
      { emoji: "📝", keywords: ["memo", "note", "write", "pencil"] },
      { emoji: "📃", keywords: ["page with curl", "document"] },
      { emoji: "📄", keywords: ["page facing up", "document"] },
      { emoji: "📑", keywords: ["bookmark tabs"] },
      { emoji: "📊", keywords: ["bar chart", "graph", "stats"] },
      { emoji: "📈", keywords: ["chart increasing", "growth", "up"] },
      { emoji: "📉", keywords: ["chart decreasing", "down"] },
      { emoji: "🗒️", keywords: ["spiral notepad"] },
      { emoji: "🗓️", keywords: ["spiral calendar"] },
      { emoji: "📆", keywords: ["tear-off calendar", "date"] },
      { emoji: "📅", keywords: ["calendar", "date"] },
      { emoji: "📇", keywords: ["card index", "rolodex"] },
      { emoji: "🗃️", keywords: ["card file box"] },
      { emoji: "🗳️", keywords: ["ballot box", "vote"] },
      { emoji: "🗄️", keywords: ["file cabinet"] },
      { emoji: "📋", keywords: ["clipboard", "paste"] },
      { emoji: "📁", keywords: ["file folder", "directory"] },
      { emoji: "📂", keywords: ["open file folder"] },
      { emoji: "🗂️", keywords: ["card index dividers"] },
      { emoji: "📰", keywords: ["newspaper", "news"] },
      { emoji: "📓", keywords: ["notebook"] },
      { emoji: "📔", keywords: ["notebook with decorative cover"] },
      { emoji: "📒", keywords: ["ledger", "notebook"] },
      { emoji: "📕", keywords: ["closed book", "red"] },
      { emoji: "📗", keywords: ["green book"] },
      { emoji: "📘", keywords: ["blue book"] },
      { emoji: "📙", keywords: ["orange book"] },
      { emoji: "📚", keywords: ["books", "library", "study"] },
      { emoji: "📖", keywords: ["open book", "read"] },
      { emoji: "🔗", keywords: ["link", "chain", "url"] },
      { emoji: "📎", keywords: ["paperclip", "attachment"] },
      { emoji: "🖇️", keywords: ["linked paperclips"] },
      { emoji: "✂️", keywords: ["scissors", "cut"] },
      { emoji: "📐", keywords: ["triangular ruler"] },
      { emoji: "📏", keywords: ["straight ruler", "measure"] },
      { emoji: "🧮", keywords: ["abacus", "calculate"] },
      { emoji: "📌", keywords: ["pushpin", "pin"] },
      { emoji: "📍", keywords: ["round pushpin", "location"] },
      { emoji: "✏️", keywords: ["pencil", "write"] },
      { emoji: "🖊️", keywords: ["pen", "write"] },
      { emoji: "🖋️", keywords: ["fountain pen", "write"] },
      { emoji: "🖌️", keywords: ["paintbrush", "art"] },
      { emoji: "🖍️", keywords: ["crayon", "draw"] },
      { emoji: "🔍", keywords: ["magnifying glass", "search", "zoom"] },
      { emoji: "🔎", keywords: ["magnifying glass right", "search"] },
    ],
  },
  symbols: {
    label: "Symbols",
    icon: "💟",
    entries: [
      { emoji: "❤️", keywords: ["red heart", "love"] },
      { emoji: "🧡", keywords: ["orange heart", "love"] },
      { emoji: "💛", keywords: ["yellow heart", "love"] },
      { emoji: "💚", keywords: ["green heart", "love"] },
      { emoji: "💙", keywords: ["blue heart", "love"] },
      { emoji: "💜", keywords: ["purple heart", "love"] },
      { emoji: "🖤", keywords: ["black heart", "love"] },
      { emoji: "🤍", keywords: ["white heart", "love"] },
      { emoji: "🤎", keywords: ["brown heart", "love"] },
      { emoji: "❤️‍🔥", keywords: ["heart on fire", "passion"] },
      { emoji: "❤️‍🩹", keywords: ["mending heart", "healing"] },
      { emoji: "💔", keywords: ["broken heart", "sad"] },
      { emoji: "💕", keywords: ["two hearts", "love"] },
      { emoji: "💞", keywords: ["revolving hearts", "love"] },
      { emoji: "💓", keywords: ["beating heart", "love"] },
      { emoji: "💗", keywords: ["growing heart", "love"] },
      { emoji: "💖", keywords: ["sparkling heart", "love"] },
      { emoji: "💘", keywords: ["heart with arrow", "cupid"] },
      { emoji: "💝", keywords: ["heart with ribbon", "gift", "love"] },
      { emoji: "💟", keywords: ["heart decoration", "love"] },
      { emoji: "☮️", keywords: ["peace", "symbol"] },
      { emoji: "✝️", keywords: ["cross", "christian", "religion"] },
      { emoji: "☪️", keywords: ["star and crescent", "islam"] },
      { emoji: "🕉️", keywords: ["om", "hindu", "buddhist"] },
      { emoji: "☸️", keywords: ["wheel of dharma", "buddhism"] },
      { emoji: "✡️", keywords: ["star of david", "jewish"] },
      { emoji: "🔯", keywords: ["six pointed star"] },
      { emoji: "🕎", keywords: ["menorah", "jewish", "hanukkah"] },
      { emoji: "☯️", keywords: ["yin yang", "balance"] },
      { emoji: "☦️", keywords: ["orthodox cross"] },
      { emoji: "🛐", keywords: ["place of worship", "pray"] },
      { emoji: "⛎", keywords: ["ophiuchus", "zodiac"] },
      { emoji: "♈", keywords: ["aries", "zodiac"] },
      { emoji: "♉", keywords: ["taurus", "zodiac"] },
      { emoji: "♊", keywords: ["gemini", "zodiac"] },
      { emoji: "♋", keywords: ["cancer", "zodiac"] },
      { emoji: "♌", keywords: ["leo", "zodiac"] },
      { emoji: "♍", keywords: ["virgo", "zodiac"] },
      { emoji: "♎", keywords: ["libra", "zodiac"] },
      { emoji: "♏", keywords: ["scorpio", "zodiac"] },
      { emoji: "♐", keywords: ["sagittarius", "zodiac"] },
      { emoji: "♑", keywords: ["capricorn", "zodiac"] },
      { emoji: "♒", keywords: ["aquarius", "zodiac"] },
      { emoji: "♓", keywords: ["pisces", "zodiac"] },
      { emoji: "🆔", keywords: ["id", "identity"] },
      { emoji: "⚛️", keywords: ["atom", "science"] },
      { emoji: "🉑", keywords: ["accept", "japanese"] },
      { emoji: "☢️", keywords: ["radioactive", "nuclear"] },
      { emoji: "☣️", keywords: ["biohazard", "danger"] },
      { emoji: "📴", keywords: ["mobile phone off"] },
      { emoji: "📳", keywords: ["vibration mode"] },
      { emoji: "🈶", keywords: ["japanese not free of charge"] },
      { emoji: "🈚", keywords: ["japanese free of charge"] },
      { emoji: "🈸", keywords: ["japanese application"] },
      { emoji: "🈺", keywords: ["japanese open for business"] },
      { emoji: "🈷️", keywords: ["japanese monthly amount"] },
      { emoji: "✴️", keywords: ["eight pointed star"] },
      { emoji: "🆚", keywords: ["vs", "versus", "against"] },
      { emoji: "💮", keywords: ["white flower", "good job"] },
      { emoji: "🉐", keywords: ["japanese bargain"] },
      { emoji: "㊙️", keywords: ["japanese secret"] },
      { emoji: "㊗️", keywords: ["japanese congratulations"] },
      { emoji: "🈴", keywords: ["japanese passing grade"] },
      { emoji: "🈵", keywords: ["japanese no vacancy"] },
      { emoji: "🈹", keywords: ["japanese discount"] },
      { emoji: "🈲", keywords: ["japanese prohibited"] },
      { emoji: "🅰️", keywords: ["a button", "blood type"] },
      { emoji: "🅱️", keywords: ["b button", "blood type"] },
      { emoji: "🆎", keywords: ["ab button", "blood type"] },
      { emoji: "🆑", keywords: ["cl button", "clear"] },
      { emoji: "🅾️", keywords: ["o button", "blood type"] },
      { emoji: "🆘", keywords: ["sos", "help", "emergency"] },
      { emoji: "❌", keywords: ["cross mark", "no", "wrong", "x"] },
      { emoji: "⭕", keywords: ["hollow red circle", "correct"] },
      { emoji: "🛑", keywords: ["stop sign", "halt"] },
      { emoji: "⛔", keywords: ["no entry", "prohibited"] },
      { emoji: "📛", keywords: ["name badge"] },
      { emoji: "🚫", keywords: ["prohibited", "forbidden", "no"] },
      { emoji: "💯", keywords: ["hundred", "perfect", "score", "100"] },
      { emoji: "💢", keywords: ["anger", "angry", "symbol"] },
      { emoji: "♨️", keywords: ["hot springs", "steam"] },
      { emoji: "🚷", keywords: ["no pedestrians"] },
      { emoji: "🚯", keywords: ["no littering"] },
      { emoji: "🚳", keywords: ["no bicycles"] },
      { emoji: "🚱", keywords: ["non-potable water"] },
      { emoji: "🔞", keywords: ["no one under eighteen", "18+"] },
      { emoji: "📵", keywords: ["no mobile phones"] },
      { emoji: "🔇", keywords: ["muted", "no sound"] },
      { emoji: "🔕", keywords: ["bell with slash", "mute"] },
      { emoji: "🔊", keywords: ["speaker high volume", "loud"] },
      { emoji: "🔉", keywords: ["speaker medium volume"] },
      { emoji: "🔈", keywords: ["speaker low volume"] },
      { emoji: "🔔", keywords: ["bell", "notification", "alert"] },
      { emoji: "♻️", keywords: ["recycling", "recycle", "green"] },
      { emoji: "✅", keywords: ["check mark", "yes", "correct", "done"] },
      { emoji: "❎", keywords: ["cross mark button", "no"] },
      { emoji: "〽️", keywords: ["part alternation mark"] },
      { emoji: "❗", keywords: ["exclamation", "warning", "important"] },
      { emoji: "❓", keywords: ["question mark"] },
      { emoji: "❕", keywords: ["white exclamation mark"] },
      { emoji: "❔", keywords: ["white question mark"] },
      { emoji: "‼️", keywords: ["double exclamation mark"] },
      { emoji: "⁉️", keywords: ["exclamation question mark"] },
      { emoji: "🔅", keywords: ["dim button", "brightness low"] },
      { emoji: "🔆", keywords: ["bright button", "brightness high"] },
      { emoji: "⚠️", keywords: ["warning", "caution", "alert"] },
      { emoji: "🚸", keywords: ["children crossing"] },
      { emoji: "🔱", keywords: ["trident", "emblem"] },
      { emoji: "⚜️", keywords: ["fleur-de-lis"] },
      { emoji: "🔰", keywords: ["japanese symbol for beginner"] },
      { emoji: "♿", keywords: ["wheelchair", "accessibility"] },
      { emoji: "🏧", keywords: ["atm sign"] },
      { emoji: "Ⓜ️", keywords: ["circled m", "metro"] },
      { emoji: "🛂", keywords: ["passport control"] },
      { emoji: "🛃", keywords: ["customs"] },
      { emoji: "🛄", keywords: ["baggage claim"] },
      { emoji: "🛅", keywords: ["left luggage"] },
      { emoji: "🔠", keywords: ["input latin uppercase"] },
      { emoji: "🔡", keywords: ["input latin lowercase"] },
      { emoji: "🔢", keywords: ["input numbers"] },
      { emoji: "🔣", keywords: ["input symbols"] },
      { emoji: "🔤", keywords: ["input latin letters"] },
      { emoji: "ℹ️", keywords: ["information", "info"] },
      { emoji: "🆗", keywords: ["ok button"] },
      { emoji: "🆕", keywords: ["new button"] },
      { emoji: "🆙", keywords: ["up button", "upgrade"] },
      { emoji: "🆒", keywords: ["cool button"] },
      { emoji: "🆓", keywords: ["free button"] },
      { emoji: "🆖", keywords: ["ng button", "no good"] },
      { emoji: "🅿️", keywords: ["p button", "parking"] },
      { emoji: "🈁", keywords: ["japanese here"] },
      { emoji: "🈂️", keywords: ["japanese service charge"] },
      { emoji: "🈳", keywords: ["japanese vacancy"] },
      { emoji: "🔃", keywords: ["clockwise arrows", "reload", "refresh"] },
      { emoji: "🔄", keywords: ["counterclockwise arrows", "refresh"] },
      { emoji: "🔙", keywords: ["back arrow"] },
      { emoji: "🔚", keywords: ["end arrow"] },
      { emoji: "🔛", keywords: ["on arrow"] },
      { emoji: "🔜", keywords: ["soon arrow"] },
      { emoji: "🔝", keywords: ["top arrow"] },
      { emoji: "⬆️", keywords: ["up arrow"] },
      { emoji: "⬇️", keywords: ["down arrow"] },
      { emoji: "⬅️", keywords: ["left arrow"] },
      { emoji: "➡️", keywords: ["right arrow"] },
      { emoji: "↗️", keywords: ["up-right arrow"] },
      { emoji: "↘️", keywords: ["down-right arrow"] },
      { emoji: "↙️", keywords: ["down-left arrow"] },
      { emoji: "↖️", keywords: ["up-left arrow"] },
      { emoji: "↕️", keywords: ["up-down arrow"] },
      { emoji: "↔️", keywords: ["left-right arrow"] },
      { emoji: "↩️", keywords: ["right arrow curving left", "undo"] },
      { emoji: "↪️", keywords: ["left arrow curving right", "redo"] },
      { emoji: "⤴️", keywords: ["right arrow curving up"] },
      { emoji: "⤵️", keywords: ["right arrow curving down"] },
      { emoji: "🔀", keywords: ["shuffle", "random"] },
      { emoji: "🔁", keywords: ["repeat", "loop"] },
      { emoji: "🔂", keywords: ["repeat single"] },
      { emoji: "▶️", keywords: ["play button", "start"] },
      { emoji: "⏩", keywords: ["fast forward"] },
      { emoji: "⏭️", keywords: ["next track button"] },
      { emoji: "⏯️", keywords: ["play or pause button"] },
      { emoji: "◀️", keywords: ["reverse button", "back"] },
      { emoji: "⏪", keywords: ["fast reverse", "rewind"] },
      { emoji: "⏮️", keywords: ["last track button"] },
      { emoji: "⏸️", keywords: ["pause button"] },
      { emoji: "⏹️", keywords: ["stop button"] },
      { emoji: "⏺️", keywords: ["record button"] },
      { emoji: "⏏️", keywords: ["eject button"] },
      { emoji: "🎵", keywords: ["musical note", "music", "song"] },
      { emoji: "🎶", keywords: ["musical notes", "music", "singing"] },
      { emoji: "➕", keywords: ["plus", "add"] },
      { emoji: "➖", keywords: ["minus", "subtract"] },
      { emoji: "➗", keywords: ["divide", "division"] },
      { emoji: "✖️", keywords: ["multiply", "times"] },
      { emoji: "♾️", keywords: ["infinity", "forever"] },
      { emoji: "💲", keywords: ["dollar sign", "money"] },
      { emoji: "💱", keywords: ["currency exchange"] },
      { emoji: "™️", keywords: ["trade mark", "tm"] },
      { emoji: "©️", keywords: ["copyright"] },
      { emoji: "®️", keywords: ["registered"] },
      { emoji: "〰️", keywords: ["wavy dash"] },
      { emoji: "➰", keywords: ["curly loop"] },
      { emoji: "➿", keywords: ["double curly loop"] },
      { emoji: "#️⃣", keywords: ["keycap hash", "number sign", "hashtag"] },
      { emoji: "*️⃣", keywords: ["keycap asterisk", "star"] },
      { emoji: "0️⃣", keywords: ["keycap zero", "0"] },
      { emoji: "1️⃣", keywords: ["keycap one", "1"] },
      { emoji: "2️⃣", keywords: ["keycap two", "2"] },
      { emoji: "3️⃣", keywords: ["keycap three", "3"] },
      { emoji: "4️⃣", keywords: ["keycap four", "4"] },
      { emoji: "5️⃣", keywords: ["keycap five", "5"] },
      { emoji: "6️⃣", keywords: ["keycap six", "6"] },
      { emoji: "7️⃣", keywords: ["keycap seven", "7"] },
      { emoji: "8️⃣", keywords: ["keycap eight", "8"] },
      { emoji: "9️⃣", keywords: ["keycap nine", "9"] },
      { emoji: "🔟", keywords: ["keycap ten", "10"] },
      { emoji: "🔶", keywords: ["large orange diamond"] },
      { emoji: "🔷", keywords: ["large blue diamond"] },
      { emoji: "🔸", keywords: ["small orange diamond"] },
      { emoji: "🔹", keywords: ["small blue diamond"] },
      { emoji: "🔺", keywords: ["red triangle up"] },
      { emoji: "🔻", keywords: ["red triangle down"] },
      { emoji: "◾", keywords: ["black medium-small square"] },
      { emoji: "◽", keywords: ["white medium-small square"] },
      { emoji: "⬛", keywords: ["black large square"] },
      { emoji: "⬜", keywords: ["white large square"] },
      { emoji: "🟥", keywords: ["red square"] },
      { emoji: "🟧", keywords: ["orange square"] },
      { emoji: "🟨", keywords: ["yellow square"] },
      { emoji: "🟩", keywords: ["green square"] },
      { emoji: "🟦", keywords: ["blue square"] },
      { emoji: "🟪", keywords: ["purple square"] },
      { emoji: "🟫", keywords: ["brown square"] },
      { emoji: "🔴", keywords: ["red circle"] },
      { emoji: "🟠", keywords: ["orange circle"] },
      { emoji: "🟡", keywords: ["yellow circle"] },
      { emoji: "🟢", keywords: ["green circle"] },
      { emoji: "🔵", keywords: ["blue circle"] },
      { emoji: "🟣", keywords: ["purple circle"] },
      { emoji: "🟤", keywords: ["brown circle"] },
      { emoji: "⚫", keywords: ["black circle"] },
      { emoji: "⚪", keywords: ["white circle"] },
    ],
  },
  activities: {
    label: "Activities",
    icon: "⚽",
    entries: [
      { emoji: "⚽", keywords: ["soccer", "football", "ball", "sport"] },
      { emoji: "🏀", keywords: ["basketball", "ball", "sport"] },
      { emoji: "🏈", keywords: ["american football", "ball", "sport"] },
      { emoji: "⚾", keywords: ["baseball", "ball", "sport"] },
      { emoji: "🥎", keywords: ["softball", "ball"] },
      { emoji: "🎾", keywords: ["tennis", "ball", "sport"] },
      { emoji: "🏐", keywords: ["volleyball", "ball", "sport"] },
      { emoji: "🏉", keywords: ["rugby", "ball", "sport"] },
      { emoji: "🥏", keywords: ["flying disc", "frisbee"] },
      { emoji: "🎱", keywords: ["billiards", "pool", "8 ball"] },
      { emoji: "🪀", keywords: ["yo-yo", "toy"] },
      { emoji: "🏓", keywords: ["ping pong", "table tennis"] },
      { emoji: "🏸", keywords: ["badminton", "shuttlecock"] },
      { emoji: "🏒", keywords: ["ice hockey", "stick"] },
      { emoji: "🏑", keywords: ["field hockey", "stick"] },
      { emoji: "🥍", keywords: ["lacrosse", "stick"] },
      { emoji: "🏏", keywords: ["cricket", "bat"] },
      { emoji: "🪃", keywords: ["boomerang"] },
      { emoji: "🥅", keywords: ["goal net", "soccer"] },
      { emoji: "⛳", keywords: ["golf", "flag in hole"] },
      { emoji: "🪁", keywords: ["kite", "fly"] },
      { emoji: "🏹", keywords: ["bow and arrow", "archery"] },
      { emoji: "🎣", keywords: ["fishing", "rod"] },
      { emoji: "🤿", keywords: ["diving mask", "scuba", "snorkel"] },
      { emoji: "🥊", keywords: ["boxing glove", "fight"] },
      { emoji: "🥋", keywords: ["martial arts", "karate", "uniform"] },
      { emoji: "🎿", keywords: ["skis", "skiing", "snow"] },
      { emoji: "⛸️", keywords: ["ice skate", "skating"] },
      { emoji: "🛷", keywords: ["sled", "sledge"] },
      { emoji: "🛹", keywords: ["skateboard", "skate"] },
      { emoji: "🛼", keywords: ["roller skate"] },
      { emoji: "🎪", keywords: ["circus tent"] },
      { emoji: "🎭", keywords: ["performing arts", "theater", "drama"] },
      { emoji: "🎨", keywords: ["art", "palette", "paint"] },
      { emoji: "🎬", keywords: ["clapper board", "movie", "film"] },
      { emoji: "🎤", keywords: ["microphone", "karaoke", "sing"] },
      { emoji: "🎧", keywords: ["headphones", "music", "listen"] },
      { emoji: "🎼", keywords: ["musical score", "music", "sheet"] },
      { emoji: "🎹", keywords: ["musical keyboard", "piano"] },
      { emoji: "🥁", keywords: ["drum", "beat", "percussion"] },
      { emoji: "🪘", keywords: ["long drum"] },
      { emoji: "🎷", keywords: ["saxophone", "jazz", "music"] },
      { emoji: "🎺", keywords: ["trumpet", "brass", "music"] },
      { emoji: "🪗", keywords: ["accordion"] },
      { emoji: "🎸", keywords: ["guitar", "rock", "music"] },
      { emoji: "🪕", keywords: ["banjo", "music"] },
      { emoji: "🎻", keywords: ["violin", "music"] },
      { emoji: "🎲", keywords: ["dice", "game", "gamble"] },
      { emoji: "♟️", keywords: ["chess pawn", "game"] },
      { emoji: "🎯", keywords: ["bullseye", "target", "dart"] },
      { emoji: "🎳", keywords: ["bowling", "sport"] },
      { emoji: "🎮", keywords: ["video game", "controller", "gaming"] },
      { emoji: "🕹️", keywords: ["joystick", "arcade", "game"] },
      { emoji: "🎰", keywords: ["slot machine", "casino", "gamble"] },
      { emoji: "🧩", keywords: ["puzzle", "piece", "jigsaw"] },
      { emoji: "🧸", keywords: ["teddy bear", "toy", "plush"] },
      { emoji: "🪅", keywords: ["piñata", "party"] },
      { emoji: "🪩", keywords: ["mirror ball", "disco"] },
      { emoji: "🪆", keywords: ["nesting dolls", "matryoshka"] },
      { emoji: "♠️", keywords: ["spade suit", "cards"] },
      { emoji: "♥️", keywords: ["heart suit", "cards"] },
      { emoji: "♦️", keywords: ["diamond suit", "cards"] },
      { emoji: "♣️", keywords: ["club suit", "cards"] },
      { emoji: "🃏", keywords: ["joker", "card", "wild"] },
      { emoji: "🀄", keywords: ["mahjong", "game"] },
      { emoji: "🎴", keywords: ["flower playing cards"] },
      { emoji: "🎉", keywords: ["party popper", "celebrate", "tada"] },
      { emoji: "🎊", keywords: ["confetti ball", "celebrate"] },
      { emoji: "🎈", keywords: ["balloon", "party", "birthday"] },
      { emoji: "🎁", keywords: ["gift", "present", "wrapped"] },
      { emoji: "🎀", keywords: ["ribbon", "bow", "decoration"] },
      { emoji: "🏆", keywords: ["trophy", "winner", "champion", "award"] },
      { emoji: "🥇", keywords: ["gold medal", "first", "winner"] },
      { emoji: "🥈", keywords: ["silver medal", "second"] },
      { emoji: "🥉", keywords: ["bronze medal", "third"] },
      { emoji: "🏅", keywords: ["sports medal", "award"] },
      { emoji: "🎖️", keywords: ["military medal", "honor"] },
      { emoji: "🎗️", keywords: ["reminder ribbon", "awareness"] },
      { emoji: "🎟️", keywords: ["admission tickets"] },
      { emoji: "🎫", keywords: ["ticket", "admission"] },
      { emoji: "🎆", keywords: ["fireworks", "celebrate", "new year"] },
      { emoji: "🎇", keywords: ["sparkler", "fireworks"] },
      { emoji: "🧨", keywords: ["firecracker", "dynamite"] },
      { emoji: "🎑", keywords: ["moon viewing", "ceremony"] },
      { emoji: "🎃", keywords: ["jack-o-lantern", "halloween", "pumpkin"] },
      { emoji: "🎄", keywords: ["christmas tree", "holiday"] },
      { emoji: "🎋", keywords: ["tanabata tree"] },
      { emoji: "🎍", keywords: ["pine decoration", "new year"] },
      { emoji: "🎎", keywords: ["japanese dolls"] },
      { emoji: "🎏", keywords: ["carp streamer", "koinobori"] },
      { emoji: "🎐", keywords: ["wind chime"] },
      { emoji: "🎌", keywords: ["crossed flags"] },
      { emoji: "🏮", keywords: ["red paper lantern", "izakaya"] },
      { emoji: "🧧", keywords: ["red envelope", "lucky money"] },
    ],
  },
  flags: {
    label: "Flags",
    icon: "🏳️",
    entries: [
      { emoji: "🏁", keywords: ["chequered flag", "race", "finish"] },
      { emoji: "🚩", keywords: ["triangular flag", "red flag"] },
      { emoji: "🎌", keywords: ["crossed flags"] },
      { emoji: "🏴", keywords: ["black flag"] },
      { emoji: "🏳️", keywords: ["white flag", "surrender"] },
      { emoji: "🏳️‍🌈", keywords: ["rainbow flag", "pride", "lgbtq"] },
      { emoji: "🏳️‍⚧️", keywords: ["transgender flag", "trans"] },
      { emoji: "🏴‍☠️", keywords: ["pirate flag", "jolly roger"] },
      { emoji: "🇦🇫", keywords: ["afghanistan", "flag"] },
      { emoji: "🇦🇱", keywords: ["albania", "flag"] },
      { emoji: "🇩🇿", keywords: ["algeria", "flag"] },
      { emoji: "🇦🇷", keywords: ["argentina", "flag"] },
      { emoji: "🇦🇺", keywords: ["australia", "flag"] },
      { emoji: "🇦🇹", keywords: ["austria", "flag"] },
      { emoji: "🇧🇩", keywords: ["bangladesh", "flag"] },
      { emoji: "🇧🇪", keywords: ["belgium", "flag"] },
      { emoji: "🇧🇷", keywords: ["brazil", "flag"] },
      { emoji: "🇨🇦", keywords: ["canada", "flag"] },
      { emoji: "🇨🇱", keywords: ["chile", "flag"] },
      { emoji: "🇨🇳", keywords: ["china", "flag"] },
      { emoji: "🇨🇴", keywords: ["colombia", "flag"] },
      { emoji: "🇭🇷", keywords: ["croatia", "flag"] },
      { emoji: "🇨🇺", keywords: ["cuba", "flag"] },
      { emoji: "🇨🇿", keywords: ["czech republic", "czechia", "flag"] },
      { emoji: "🇩🇰", keywords: ["denmark", "flag"] },
      { emoji: "🇪🇬", keywords: ["egypt", "flag"] },
      { emoji: "🇪🇹", keywords: ["ethiopia", "flag"] },
      { emoji: "🇫🇮", keywords: ["finland", "flag"] },
      { emoji: "🇫🇷", keywords: ["france", "french", "flag"] },
      { emoji: "🇩🇪", keywords: ["germany", "flag"] },
      { emoji: "🇬🇷", keywords: ["greece", "flag"] },
      { emoji: "🇭🇰", keywords: ["hong kong", "flag"] },
      { emoji: "🇭🇺", keywords: ["hungary", "flag"] },
      { emoji: "🇮🇸", keywords: ["iceland", "flag"] },
      { emoji: "🇮🇳", keywords: ["india", "flag"] },
      { emoji: "🇮🇩", keywords: ["indonesia", "flag"] },
      { emoji: "🇮🇷", keywords: ["iran", "flag"] },
      { emoji: "🇮🇶", keywords: ["iraq", "flag"] },
      { emoji: "🇮🇪", keywords: ["ireland", "flag"] },
      { emoji: "🇮🇱", keywords: ["israel", "flag"] },
      { emoji: "🇮🇹", keywords: ["italy", "flag"] },
      { emoji: "🇯🇲", keywords: ["jamaica", "flag"] },
      { emoji: "🇯🇵", keywords: ["japan", "flag"] },
      { emoji: "🇯🇴", keywords: ["jordan", "flag"] },
      { emoji: "🇰🇪", keywords: ["kenya", "flag"] },
      { emoji: "🇰🇵", keywords: ["north korea", "flag"] },
      { emoji: "🇰🇷", keywords: ["south korea", "korea", "flag"] },
      { emoji: "🇰🇼", keywords: ["kuwait", "flag"] },
      { emoji: "🇱🇧", keywords: ["lebanon", "flag"] },
      { emoji: "🇲🇾", keywords: ["malaysia", "flag"] },
      { emoji: "🇲🇽", keywords: ["mexico", "flag"] },
      { emoji: "🇲🇦", keywords: ["morocco", "flag"] },
      { emoji: "🇳🇱", keywords: ["netherlands", "dutch", "flag"] },
      { emoji: "🇳🇿", keywords: ["new zealand", "flag"] },
      { emoji: "🇳🇬", keywords: ["nigeria", "flag"] },
      { emoji: "🇳🇴", keywords: ["norway", "flag"] },
      { emoji: "🇵🇰", keywords: ["pakistan", "flag"] },
      { emoji: "🇵🇭", keywords: ["philippines", "flag"] },
      { emoji: "🇵🇱", keywords: ["poland", "flag"] },
      { emoji: "🇵🇹", keywords: ["portugal", "flag"] },
      { emoji: "🇶🇦", keywords: ["qatar", "flag"] },
      { emoji: "🇷🇴", keywords: ["romania", "flag"] },
      { emoji: "🇷🇺", keywords: ["russia", "flag"] },
      { emoji: "🇸🇦", keywords: ["saudi arabia", "flag"] },
      { emoji: "🇸🇬", keywords: ["singapore", "flag"] },
      { emoji: "🇿🇦", keywords: ["south africa", "flag"] },
      { emoji: "🇪🇸", keywords: ["spain", "flag"] },
      { emoji: "🇸🇪", keywords: ["sweden", "flag"] },
      { emoji: "🇨🇭", keywords: ["switzerland", "flag"] },
      { emoji: "🇹🇼", keywords: ["taiwan", "flag"] },
      { emoji: "🇹🇭", keywords: ["thailand", "flag"] },
      { emoji: "🇹🇷", keywords: ["turkey", "turkiye", "flag"] },
      { emoji: "🇺🇦", keywords: ["ukraine", "flag"] },
      { emoji: "🇦🇪", keywords: ["united arab emirates", "uae", "flag"] },
      { emoji: "🇬🇧", keywords: ["united kingdom", "uk", "britain", "flag"] },
      { emoji: "🇺🇸", keywords: ["united states", "usa", "america", "flag"] },
      { emoji: "🇻🇳", keywords: ["vietnam", "flag"] },
      { emoji: "🇪🇺", keywords: ["european union", "eu", "flag"] },
      { emoji: "🇺🇳", keywords: ["united nations", "un", "flag"] },
    ],
  },
};

export function get_all_emojis(): EmojiEntry[] {
  return Object.values(emoji_categories).flatMap(
    (category) => category.entries,
  );
}

export function search_emojis(query: string): EmojiEntry[] {
  const lower = query.toLowerCase().trim();

  if (!lower) return [];

  return get_all_emojis().filter(
    (entry) =>
      entry.emoji.includes(lower) ||
      entry.keywords.some((kw) => kw.includes(lower)),
  );
}
