//
// Aster Communications Inc.
//
// Copyright (c) 2026 Aster Communications Inc.
//
// This file is part of this project.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the AGPLv3 as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// AGPLv3 for more details.
//
// You should have received a copy of the AGPLv3
// along with this program. If not, see <https://www.gnu.org/licenses/>.
//

#[cfg(windows)]
pub const BADGES: [&[u8]; 100] = [
    include_bytes!("../badges/b1.png"),
    include_bytes!("../badges/b2.png"),
    include_bytes!("../badges/b3.png"),
    include_bytes!("../badges/b4.png"),
    include_bytes!("../badges/b5.png"),
    include_bytes!("../badges/b6.png"),
    include_bytes!("../badges/b7.png"),
    include_bytes!("../badges/b8.png"),
    include_bytes!("../badges/b9.png"),
    include_bytes!("../badges/b10.png"),
    include_bytes!("../badges/b11.png"),
    include_bytes!("../badges/b12.png"),
    include_bytes!("../badges/b13.png"),
    include_bytes!("../badges/b14.png"),
    include_bytes!("../badges/b15.png"),
    include_bytes!("../badges/b16.png"),
    include_bytes!("../badges/b17.png"),
    include_bytes!("../badges/b18.png"),
    include_bytes!("../badges/b19.png"),
    include_bytes!("../badges/b20.png"),
    include_bytes!("../badges/b21.png"),
    include_bytes!("../badges/b22.png"),
    include_bytes!("../badges/b23.png"),
    include_bytes!("../badges/b24.png"),
    include_bytes!("../badges/b25.png"),
    include_bytes!("../badges/b26.png"),
    include_bytes!("../badges/b27.png"),
    include_bytes!("../badges/b28.png"),
    include_bytes!("../badges/b29.png"),
    include_bytes!("../badges/b30.png"),
    include_bytes!("../badges/b31.png"),
    include_bytes!("../badges/b32.png"),
    include_bytes!("../badges/b33.png"),
    include_bytes!("../badges/b34.png"),
    include_bytes!("../badges/b35.png"),
    include_bytes!("../badges/b36.png"),
    include_bytes!("../badges/b37.png"),
    include_bytes!("../badges/b38.png"),
    include_bytes!("../badges/b39.png"),
    include_bytes!("../badges/b40.png"),
    include_bytes!("../badges/b41.png"),
    include_bytes!("../badges/b42.png"),
    include_bytes!("../badges/b43.png"),
    include_bytes!("../badges/b44.png"),
    include_bytes!("../badges/b45.png"),
    include_bytes!("../badges/b46.png"),
    include_bytes!("../badges/b47.png"),
    include_bytes!("../badges/b48.png"),
    include_bytes!("../badges/b49.png"),
    include_bytes!("../badges/b50.png"),
    include_bytes!("../badges/b51.png"),
    include_bytes!("../badges/b52.png"),
    include_bytes!("../badges/b53.png"),
    include_bytes!("../badges/b54.png"),
    include_bytes!("../badges/b55.png"),
    include_bytes!("../badges/b56.png"),
    include_bytes!("../badges/b57.png"),
    include_bytes!("../badges/b58.png"),
    include_bytes!("../badges/b59.png"),
    include_bytes!("../badges/b60.png"),
    include_bytes!("../badges/b61.png"),
    include_bytes!("../badges/b62.png"),
    include_bytes!("../badges/b63.png"),
    include_bytes!("../badges/b64.png"),
    include_bytes!("../badges/b65.png"),
    include_bytes!("../badges/b66.png"),
    include_bytes!("../badges/b67.png"),
    include_bytes!("../badges/b68.png"),
    include_bytes!("../badges/b69.png"),
    include_bytes!("../badges/b70.png"),
    include_bytes!("../badges/b71.png"),
    include_bytes!("../badges/b72.png"),
    include_bytes!("../badges/b73.png"),
    include_bytes!("../badges/b74.png"),
    include_bytes!("../badges/b75.png"),
    include_bytes!("../badges/b76.png"),
    include_bytes!("../badges/b77.png"),
    include_bytes!("../badges/b78.png"),
    include_bytes!("../badges/b79.png"),
    include_bytes!("../badges/b80.png"),
    include_bytes!("../badges/b81.png"),
    include_bytes!("../badges/b82.png"),
    include_bytes!("../badges/b83.png"),
    include_bytes!("../badges/b84.png"),
    include_bytes!("../badges/b85.png"),
    include_bytes!("../badges/b86.png"),
    include_bytes!("../badges/b87.png"),
    include_bytes!("../badges/b88.png"),
    include_bytes!("../badges/b89.png"),
    include_bytes!("../badges/b90.png"),
    include_bytes!("../badges/b91.png"),
    include_bytes!("../badges/b92.png"),
    include_bytes!("../badges/b93.png"),
    include_bytes!("../badges/b94.png"),
    include_bytes!("../badges/b95.png"),
    include_bytes!("../badges/b96.png"),
    include_bytes!("../badges/b97.png"),
    include_bytes!("../badges/b98.png"),
    include_bytes!("../badges/b99.png"),
    include_bytes!("../badges/b100.png"),
];
